#--------------------------
# dojo profile config
# https://book.dojoengine.org/framework/config
# https://github.com/dojoengine/dojo/blob/main/examples/simple/dojo_dev.toml
#

[world]
name = "Pistols at Dawn"
description = "An on-chain pistol duelling game of honour and betrayal."
icon_uri = "https://assets.underware.gg/pistols/logo.png"
cover_uri = "https://assets.underware.gg/pistols/splash.jpg"
website = "https://pistols.gg"
seed = "pistols"

[world.socials]
x = "https://x.com/pistols_gg"
github = "https://github.com/underware-gg/pistols"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://127.0.0.1:5050"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x05fa5438c7ccbcbae63ec200779acf8b71f34f432e9f0e7adec7a74230850c6b"
world_block = 1

# development options
[cartridge]
controllers = true
# paymaster = true

#--------------------------
# namespaces
#
[namespace]
default = "pistols"

#--------------------------
# namespaces
#
[owners]
"pistols" = [
  "pistols-game",
  "pistols-admin",
]

#--------------------------
# writers
#
[writers]
"pistols" = [
  "pistols-game",
  "pistols-tutorial",
  "pistols-admin",
  "pistols-duel_token",
  "pistols-duelist_token",
  "pistols-pack_token",
  "pistols-ring_token",
  # "pistols-tournament_token",
  "pistols-bank",
  "pistols-matchmaker",
]
# ERC-20
"pistols-CoinConfig" = [
  "pistols-fame_coin",
  "pistols-fools_coin",
  "pistols-lords_mock",
]
"pistols-TokenBoundAddress" = ["pistols-fame_coin"]
# arcade trophies
"pistols-TrophyCreation" = ["pistols-game"]
"pistols-TrophyProgression" = ["pistols-game"]
# # mocks
# "pistols-MockedValue" = ["pistols-budokan_mock"]

#--------------------------
# init_calldata
#
[init_call_args]
"pistols-admin" = [
  "0x0", # treasury_address (or initializer)
  "0x0", # lords_address (use lords_mock)
  "0x0", # vrf_address (use vrf_mock)
]
"pistols-duel_token" = [
  # "sstr:http://localhost:3000", # base_uri
  "sstr:https://assets.underware.gg", # base_uri
  "0x0", # minter_address
]
"pistols-duelist_token" = [
  # "sstr:http://localhost:3000", # base_uri
  "sstr:https://assets.underware.gg", # base_uri
]
"pistols-pack_token" = [
  # "sstr:http://localhost:3000", # base_uri
  "sstr:https://assets.underware.gg", # base_uri
]
"pistols-ring_token" = [
  # "sstr:http://localhost:3000", # base_uri
  "sstr:https://assets.underware.gg", # base_uri
]
# "pistols-tournament_token" = [
#   # "sstr:http://localhost:3000", # base_uri
#   "sstr:https://assets.underware.gg", # base_uri
# ]
"pistols-lords_mock" = [
  "0x0", # minter_address
  "10000000000000000000000", # faucet_amount: 10,000 LORDS
]


#--------------------------
# migration
#
[migration]
order_inits = []
skip_contracts = []
