packages:
  - "sdk"
  - "client"
  # - "dreams"
  - "verifier"

catalog:
  #--------------------------------
  # dojo.js
  #
  "@dojoengine/core": 1.5.6
  "@dojoengine/sdk": 1.5.6
  "@dojoengine/torii-client": 1.5.6
  "@dojoengine/utils": 1.5.6
  # "@dojoengine/core": ../../dojo.js/packages/core
  # "@dojoengine/sdk": ../../dojo.js/packages/sdk
  # "@dojoengine/torii-client": ../../dojo.js/packages/torii-client
  # "@dojoengine/utils": ../../dojo.js/packages/utils

  #--------------------------------
  # same as dojo.js
  # https://github.com/dojoengine/dojo.js/blob/main/pnpm-workspace.yaml
  #
  "@starknet-react/core": ^3.6.2
  "@starknet-react/chains": ^3.1.0
  "@tanstack/react-query": ^5.62.16
  get-starknet-core: ^4.0.0
  starknet: 6.23.1
  immer: ^10.1.1
  zustand: ^4.5.5
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
  
  #--------------------------------
  # misc
  #
  "@cartridge/connector": 0.7.13
  "@cartridge/controller": 0.7.13
  "@cartridge/presets": 0.5.4
  "@apollo/client": ^3.11.8
  "@types/node": "^22.10.2"
  starknetid.js: ^4.0.0
  typescript: ^5.5.4
  tsup: ^8.3.5
  universal-cookie: "^8.0.1"

  # daydreams
  "@daydreamsai/core": ^0.0.4
  # "@daydreamsai/core": ../../daydreams/packages/core
