packages:
  - 'client'
  - 'sdk'

catalog:
  '@apollo/client': ^3.11.8
  '@cartridge/connector': 0.5.7
  '@cartridge/controller': 0.5.7
  '@dojoengine/core': 1.0.9
  '@dojoengine/sdk': 1.0.9
  '@dojoengine/torii-client': 1.0.9
  '@dojoengine/utils': 1.0.9
  '@starknet-react/chains': ^3.1.0
  '@starknet-react/core': ^3.6.2
  get-starknet-core: ^4.0.0
  immer: ^10.1.1
  react: ^18.2.0
  react-dom: ^18.2.0
  starknet: ^6.11.0
  starknetid.js: ^4.0.0
  typescript: ^5.5.4
  zustand: ^4.5.5
