packages:
  - "sdk"
  - "client"
  # - "dreams"
  - "verifier"

catalog:
  #--------------------------------
  # dojo.js
  #
  "@dojoengine/core": 1.8.0
  "@dojoengine/sdk": 1.8.0
  "@dojoengine/torii-client": 1.8.0
  "@dojoengine/utils": 1.8.0
  # "@dojoengine/core": ../../dojo4js/packages/core
  # "@dojoengine/sdk": ../../dojo.js/packages/sdk
  # "@dojoengine/torii-client": ../../dojo.js/packages/torii-client
  # "@dojoengine/utils": ../../dojo.js/packages/utils

  #--------------------------------
  # same as dojo.js
  # https://github.com/dojoengine/dojo.js/blob/main/pnpm-workspace.yaml
  #
  "@starknet-react/core": ^5.0.1
  "@starknet-react/chains": ^5.0.1
  "@tanstack/react-query": ^5.62.16
  "@starknet-io/get-starknet-core": 4.0.7
  starknet: ^8.5.4
  immer: ^10.1.1
  zustand: ^4.5.6
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
  
  #--------------------------------
  # misc
  #
  "@cartridge/connector": 0.10.7
  "@cartridge/controller": 0.10.7
  "@cartridge/presets": 0.5.4
  "@apollo/client": ^3.11.8
  "@types/node": "^22.10.2"
  starknetid.js: ^5.0.0
  typescript: ^5.5.4
  tsup: ^8.3.5
  universal-cookie: "^8.0.1"

  # daydreams
  "@daydreamsai/core": ^0.0.4
  # "@daydreamsai/core": ../../daydreams/packages/core
