packages:
  - 'client'
  - 'sdk'

catalog:
  '@dojoengine/core': 1.0.2
  '@dojoengine/sdk': 1.0.2
  '@dojoengine/torii-client': 1.0.2
  '@dojoengine/utils': 1.0.2
  react: ^18.2.0
  react-dom: ^18.2.0
  typescript: ^5.5.4
