tag = "pistols-lords_mock"
writes = [
  "origami_token-SRC5Model",
  "origami_token-InitializableModel",
  "origami_token-ERC20BalanceModel",
  "origami_token-ERC20MetadataModel",
  "origami_token-ERC20AllowanceModel",
  "origami_token-ERC20BridgeableModel",
]
init_calldata = []
