#!/bin/bash
set -euo pipefail
source scripts/setup.sh

# Use mocked Lords if lords_address not defined in Scarb
export LORDS_ADDRESS=$(toml get Scarb.toml --raw profile.$PROFILE.tool.dojo.env.lords_address)
if [[ -z "$LORDS_ADDRESS" ]]; then
  echo "* using mock \$LORDS 👑"
  export LORDS_ADDRESS=$(get_contract_address "pistols-lords_mock")
  export LORDS_MOCK="Yes"
fi

echo "------------------------------------------------------------------------------"
echo "::admin     : $ADMIN_ADDRESS"
echo "::game      : $GAME_ADDRESS"
echo "\$LORDS      : $LORDS_ADDRESS"
echo "\$LORDS Mock : $LORDS_MOCK"
echo "------------------------------------------------------------------------------"

if [[
  -z "$PROFILE" ||
  -z "$MANIFEST_FILE_PATH" ||
  "$ACCOUNT_ADDRESS" != "0x"* ||
  "$WORLD_ADDRESS" != "0x"* ||
  "$ADMIN_ADDRESS" != "0x"* ||
  "$GAME_ADDRESS" != "0x"* ||
  "$LORDS_ADDRESS" != "0x"*
]]; then
  echo "! Missing data 👎"
  exit 1
fi

# Lords
printf "LORDS.is_initialized() : "
sozo --profile $PROFILE call --world $WORLD_ADDRESS $LORDS_ADDRESS is_initialized
printf "LORDS.balance_of(account) : "
sozo --profile $PROFILE call --world $WORLD_ADDRESS $LORDS_ADDRESS balance_of --calldata $ACCOUNT_ADDRESS
printf "LORDS.balance_of(0xxxxx) : "
sozo --profile $PROFILE call --world $WORLD_ADDRESS $LORDS_ADDRESS balance_of --calldata 0x120e7b1e5e47526b5b11bd0be67742ee45e8fc02a275a4ec641a8f0b673b04c

# Admin
printf "ADMIN.is_initialized() : "
sozo --profile $PROFILE call --world $WORLD_ADDRESS $ADMIN_ADDRESS is_initialized
