[world]
name = "Pistols at 10 Blocks"
description = "An on-chain pistol duelling game of honour and betrayal."
icon_uri = "https://pistols.underware.gg/images/logo.png"
cover_uri = "https://pistols.underware.gg/images/splash.png"
website = "https://pistols.underware.gg"
seed = "pistols"

[world.socials]
x = "https://x.com/underware_gg"
github = "https://github.com/underware-gg/pistols"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[namespace]
default = "pistols"

[env]
chain_id = "WP_PISTOLS_STAGING"
rpc_url = "https://api.cartridge.gg/x/pistols-staging/katana"
account_address = "0x9dce42a35cd13e599b35eb3c044658e378755f99e8e60fcd2c07b7551180f5"
private_key = "0x76ba22d3b0daaed7b9aea40ce7dff297e73aab9a70d4e2359ea8d3298a4b4dc"
world_address = "0x55fefc4a4e5c94def16d25bd1afa87407d114600560f75100f3edc8d5eaced6"
