#--------------------------
# dojo profile config
# https://book.dojoengine.org/framework/config
# https://github.com/dojoengine/dojo/blob/main/examples/simple/dojo_dev.toml
#

[world]
name = "Pistols at Dawn"
description = "An on-chain pistol duelling game of honour and betrayal."
icon_uri = "https://pistols.underware.gg/images/logo.png"
cover_uri = "https://pistols.underware.gg/images/splash.png"
website = "https://pistols.underware.gg"
seed = "pistols"

[world.socials]
x = "https://x.com/underware_gg"
github = "https://github.com/underware-gg/pistols"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[env]
chain_id = "WP_PISTOLS_STAGING"
rpc_url = "https://api.cartridge.gg/x/pistols-staging/katana"
account_address = "0xcf5a59fce535e4fa443f59e025d81d24e8bd2bf375f6665c5aab22af1a1e27"
private_key = "0x49714ee0edbcb3fd3d1f1214e5978ada40d62ece7b84f6067ed2c7b28c972bf"
world_address = "0x1adaf57de23b6d6d43eeb42b6ab6730a022021382fef49eff1f532c21556a5a"

#--------------------------
# namespaces
#
[namespace]
default = "pistols"

#--------------------------
# namespaces
#
[owners]
"pistols" = [
  "pistols-game",
  "pistols-admin",
]

#--------------------------
# writers
#
[writers]
"pistols" = [
  "pistols-game",
  "pistols-tutorial",
  "pistols-admin",
  "pistols-duel_token",
  "pistols-duelist_token",
  "pistols-pack_token",
]
# ERC-20
"pistols-CoinConfig" = [
  "pistols-fame_coin",
  "pistols-fools_coin",
  "pistols-lords_mock",
]
"pistols-TokenBoundAddress" = ["pistols-fame_coin"]
# arcade trophies
"pistols-TrophyCreation" = ["pistols-game"]
"pistols-TrophyProgression" = ["pistols-game"]

#--------------------------
# init_calldata
#
[init_call_args]
"pistols-admin" = [
  "0x0", # treasury_address (or initializer)
  "0x044e6bcc627e6201ce09f781d1aae44ea4c21c2fdef299e34fce55bef2d02210", # lords_address (sepolia)
  "0x00be3edf412dd5982aa102524c0b8a0bcee584c5a627ed1db6a7c36922047257", # vrf_address (sepolia)
]
"pistols-duel_token" = [
  "sstr:pistols.stage.underware.gg", # base_uri
  "0x0", # minter_address
  "0x0", # renderer_address
  "0", # fee_amount
]
"pistols-duelist_token" = [
  "sstr:pistols.stage.underware.gg", # base_uri
  "0x0", # renderer_address
]
"pistols-pack_token" = [
  "sstr:pistols.stage.underware.gg", # base_uri
]


#--------------------------
# migration
#
[migration]
order_inits = []
skip_contracts = [
  "pistols-lords_mock",
  "pistols-vrf_mock",
]
