[world]
name = "Pistols at 10 Blocks"
description = "An on-chain pistol duelling game of honour and betrayal."
icon_uri = "https://pistols.underware.gg/images/logo.png"
cover_uri = "https://pistols.underware.gg/images/splash.png"
website = "https://pistols.underware.gg"
seed = "pistols"

[world.socials]
x = "https://x.com/underware_gg"
github = "https://github.com/underware-gg/pistols"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[namespace]
default = "pistols"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://localhost:5050"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address = "0x55fefc4a4e5c94def16d25bd1afa87407d114600560f75100f3edc8d5eaced6"
