#!/bin/bash
set -e

if [ $# -ge 1 ]; then
  export SERVICE_NAME=$1
else
  echo "Usage: $0 <service_name>"
  exit 1
fi

slot deployments logs $SERVICE_NAME katana -l 10
slot deployments logs $SERVICE_NAME katana -f \
  | grep -v \
  -e starknet_call \
  -e starknet_chainId \
  -e starknet_getNonce \
  -e starknet_getEvents \
  -e starknet_getClassAt \
  -e starknet_estimateFee \
  -e starknet_specVersion \
  -e starknet_getStateUpdate \
  -e starknet_blockHashAndNumber \
  -e starknet_getBlockWithTxs \
  -e starknet_getBlockWithTxHashes \
  -e starknet_getBlockWithReceipts \
  -e starknet_getTransactionStatus \
  -e starknet_getTransactionReceipt \
  -e starknet_addInvokeTransaction \
