#!/bin/bash
set -e

#sozo --offline build
sozo migrate --rpc-url https://api.cartridge.gg/x/underdark/katana --account-address 0x35d0cdaf12e6816f4a1a5c074befbddd08abf61bbea87765342289b48b4bc16 --verbose

scripts/default_auth.sh

# cp target/dev/manifest.json ../client/src/

# cd ../client
# npm run create-components

echo "--- DONE! 👍"
