#!/bin/bash
set -e # enable exit on error
source scripts/setup.sh

if [[
  -z "$PROJECT_NAME" ||
  -z "$PROFILE" ||
  -z "$MANIFEST_FILE_PATH" ||
  "$WORLD_ADDRESS" != "0x"* ||
  "$RPC_URL" != "http"*
]]; then
  echo "! Missing data 👎"
  exit 1
fi


echo "BINDINGS_PATH: $BINDINGS_PATH"
echo "CLIENT_GAME_PATH: $CLIENT_GAME_PATH"
echo "CLIENT_MANIFEST_PATH: $CLIENT_MANIFEST_PATH"

#-----------------
# build
#
echo "------------------------------------------------------------------------------"
sozo --version
echo "------------------------------------------------------------------------------"
echo ">>> Cleaning..."
sozo -P $PROFILE clean
echo ">>> Building..."
if [[ "$PROFILE" == "dev" ]]; then
  # sozo -P $PROFILE build --typescript-v2
  sozo -P $PROFILE build
else
  sozo -P $PROFILE build
fi
echo "👍"

#-----------------
# migrate
#
echo "------------------------------------------------------------------------------"
echo ">>> Migrate plan..."
set +e # disable exit on error
PLAN_OUTPUT=$(sozo -P $PROFILE migrate plan --world $WORLD_ADDRESS)
if [ "$?" != "0" ]; then
  echo "$PLAN_OUTPUT"
  exit 1
fi
set -e # enable exit on error

echo ">>> Migrate apply..."
sozo -P $PROFILE migrate apply -vvv --world $WORLD_ADDRESS
echo "👍"

#-----------------
# auth write
#
# scripts/default_auth.sh $PROFILE


#------------------------
# copy manifest to client
#
echo "------------------------------------------------------------------------------"
echo ">>> Copying manifest [$MANIFEST_FILE_PATH] to [$CLIENT_MANIFEST_PATH/]"
mkdir -p $CLIENT_MANIFEST_PATH
cp $MANIFEST_FILE_PATH $CLIENT_MANIFEST_PATH/
echo "👍"

#------------------------
# typescript bindings
#
if [[ "$PROFILE" == "dev" ]]; then
  #
  # create torii config
  export DUEL_TOKEN_ADDRESS=$(get_contract_address "pistols-duel_token")
  export DUELIST_TOKEN_ADDRESS=$(get_contract_address "pistols-duelist_token")
  echo "------------------------------------------------------------------------------"
  echo ">>> Create torii config [$TORII_CONFIG_PATH]..."
  echo "contracts = [" > $TORII_CONFIG_PATH
  echo "  { type = \"ERC721\", address = \"$DUEL_TOKEN_ADDRESS\" }, # duel_token" >> $TORII_CONFIG_PATH
  echo "  { type = \"ERC721\", address = \"$DUELIST_TOKEN_ADDRESS\" }, # duelist_token" >> $TORII_CONFIG_PATH
  echo "]" >> $TORII_CONFIG_PATH
  cat $TORII_CONFIG_PATH
  echo "👍"
  #
  # TODO: Enable this when bindings are ported
  # generate and copy bindings
  # cp -R $BINDINGS_PATH $CLIENT_GAME_PATH/
  # cp -R $BINDINGS_PATH/typescript_v2 $CLIENT_GAME_PATH/generated/
  #
  # copy to client
  echo "------------------------------------------------------------------------------"
  echo ">>> Generate sources..."
  cd ../client
  npm run create-components --game=$GAME_SLUG --profile=$PROFILE $RPC_URL $WORLD_ADDRESS
  npm run create-constants --game=$GAME_SLUG --profile=$PROFILE
  echo "👍?"
  #
  # list copied files
  echo "------------------------------------------------------------------------------"
  ls -ld $CLIENT_GAME_PATH/* | grep -E 'ts|json'
fi


#------------------
echo "--- DONE! 👍"
