#!/bin/bash
set -e
#export RUST_LOG=info
katana --version
katana \
  --chain-id KATANA_LOCAL \
  --invoke-max-steps 10000000 $* \
  --http.cors_origins "*" \
  --cartridge.paymaster \
  --dev \
  --dev.accounts 10 \
  --dev.no-fee \
  | grep -v \
  -e starknet_call \
  -e starknet_chainId \
  -e starknet_getNonce \
  -e starknet_getEvents \
  -e starknet_getClassAt \
  -e starknet_estimateFee \
  -e starknet_specVersion \
  -e starknet_getStateUpdate \
  -e starknet_blockHashAndNumber \
  -e starknet_getBlockWithTxs \
  -e starknet_getBlockWithTxHashes \
  -e starknet_getBlockWithReceipts \
  -e starknet_getTransactionStatus \
  -e starknet_getTransactionReceipt \
  -e starknet_addInvokeTransaction \
  -e "Class cache hit" \
