#!/bin/bash
set -e
#export RUST_LOG=info
katana \
  --disable-fee \
  --chain-id KATANA_LOCAL \
  --invoke-max-steps 10000000 $* \
  --allowed-origins "*" \
  --accounts 10 \
| grep -v -e starknet_call -e starknet_blockHashAndNumber -e starknet_getBlockWithTxs
