#!/bin/bash
set -e
source scripts/setup.sh

echo "@WORLD: $WORLD_ADDRESS"

if [[
  "$WORLD_ADDRESS" != "0x"*
]]; then
  echo "! Missing data 👎"
  exit 1
fi

#
# torii over https instructions
# https://web.dev/articles/how-to-use-local-https
#
# Install...
# $ brew install mkcert
# $ mkcert -install
# 
# Create certificate
# $ mkcert 0.0.0.0

torii --version
torii \
  --world $WORLD_ADDRESS $* \
  --allowed-origins "*" --index-pending \
  # --relay-local-key-path ./0.0.0.0-key.pem \
  # --relay-cert-path ./0.0.0.0.pem \
