#!/bin/bash
set -e
source scripts/setup.sh

export TORII_PATH=torii
export START_BLOCK=1

# custom params
# export WORLD_ADDRESS=0x55fefc4a4e5c94def16d25bd1afa87407d114600560f75100f3edc8d5eaced6
# export TORII_PATH=../../torii/target/debug/torii
# export START_BLOCK=720000

echo "* TORII   : $TORII_PATH"
echo "* BLOCK   : $START_BLOCK"
echo "* CFG     : $TORII_CONFIG_PATH"
echo "------------------------------------------------------------------------------"

if [[
  "$WORLD_ADDRESS" != "0x"*
]]; then
  echo "! Missing data 👎"
  exit 1
fi

#
# torii over https instructions
# https://web.dev/articles/how-to-use-local-https
#
# Install...
# $ brew install mkcert
# $ mkcert -install
# 
# Create certificate
# $ mkcert 0.0.0.0

$TORII_PATH --version
$TORII_PATH \
  --config $TORII_CONFIG_PATH \
  --http.cors_origins "*" \
  # --rpc $RPC_URL \ # in cfg file
  # --world $WORLD_ADDRESS \ # in cfg file
  # --start-block $START_BLOCK \
  # --relay-local-key-path ./0.0.0.0-key.pem \
  # --relay-cert-path ./0.0.0.0.pem \
