#
# torii config for profile [$profile]
#
world_address = "$world_address"
rpc = "$rpc_url"

[events]
raw = true
historical = [
  "pistols-PlayerActivity",
  "pistols-TrophyProgression",
]

[indexing]
index_pending = true
index_transactions = false
contracts = [
  "erc721:$duel_token", # duel_token
  "erc721:$duelist_token", # duelist_token
  "erc721:$pack_token", # pack_token
  "erc20:$fame_coin", # fame_coin
  # "erc20:$lords", # lords
]
