// Generated by dojo-bindgen on Wed, 5 Jun 2024 21:32:01 +0000. Do not modify this file manually.
import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<
            ReturnType<typeof defineContractComponents>
        >;



// Type definition for `core::integer::u256` struct
export interface U256 {
    low: BigInt;
    high: BigInt;
    
}

export const U256Definition = {
    low: RecsType.BigInt,
    high: RecsType.BigInt,
    
};

// Type definition for `token::components::token::erc20::erc20_allowance::ERC20AllowanceModel` struct
export interface ERC20AllowanceModel {
    token: BigInt;
    owner: BigInt;
    spender: BigInt;
    amount: U256;
    
}

export const ERC20AllowanceModelDefinition = {
    token: RecsType.BigInt,
    owner: RecsType.BigInt,
    spender: RecsType.BigInt,
    amount: U256Definition,
    
};


// Type definition for `pistols::models::models::Wager` struct
export interface Wager {
    duel_id: BigInt;
    value: U256;
    fee: U256;
    
}

export const WagerDefinition = {
    duel_id: RecsType.BigInt,
    value: U256Definition,
    fee: U256Definition,
    
};


// Type definition for `pistols::models::models::Pact` struct
export interface Pact {
    pair: BigInt;
    duel_id: BigInt;
    
}

export const PactDefinition = {
    pair: RecsType.BigInt,
    duel_id: RecsType.BigInt,
    
};


// Type definition for `pistols::models::config::Config` struct
export interface Config {
    key: Number;
    initialized: Boolean;
    owner_address: BigInt;
    treasury_address: BigInt;
    paused: Boolean;
    
}

export const ConfigDefinition = {
    key: RecsType.Number,
    initialized: RecsType.Boolean,
    owner_address: RecsType.BigInt,
    treasury_address: RecsType.BigInt,
    paused: RecsType.Boolean,
    
};


// Type definition for `pistols::models::models::Score` struct
export interface Score {
    honour: Number;
    level_villain: Number;
    level_trickster: Number;
    level_lord: Number;
    total_duels: Number;
    total_wins: Number;
    total_losses: Number;
    total_draws: Number;
    total_honour: Number;
    
}

export const ScoreDefinition = {
    honour: RecsType.Number,
    level_villain: RecsType.Number,
    level_trickster: RecsType.Number,
    level_lord: RecsType.Number,
    total_duels: RecsType.Number,
    total_wins: RecsType.Number,
    total_losses: RecsType.Number,
    total_draws: RecsType.Number,
    total_honour: RecsType.Number,
    
};

// Type definition for `pistols::models::models::Scoreboard` struct
export interface Scoreboard {
    address: BigInt;
    table_id: BigInt;
    score: Score;
    wager_won: U256;
    wager_lost: U256;
    
}

export const ScoreboardDefinition = {
    address: RecsType.BigInt,
    table_id: RecsType.BigInt,
    score: ScoreDefinition,
    wager_won: U256Definition,
    wager_lost: U256Definition,
    
};


// Type definition for `pistols::models::models::Shot` struct
export interface Shot {
    hash: Number;
    salt: Number;
    action: Number;
    chance_crit: Number;
    chance_hit: Number;
    dice_crit: Number;
    dice_hit: Number;
    damage: Number;
    block: Number;
    win: Number;
    wager: Number;
    health: Number;
    honour: Number;
    
}

export const ShotDefinition = {
    hash: RecsType.Number,
    salt: RecsType.Number,
    action: RecsType.Number,
    chance_crit: RecsType.Number,
    chance_hit: RecsType.Number,
    dice_crit: RecsType.Number,
    dice_hit: RecsType.Number,
    damage: RecsType.Number,
    block: RecsType.Number,
    win: RecsType.Number,
    wager: RecsType.Number,
    health: RecsType.Number,
    honour: RecsType.Number,
    
};

// Type definition for `pistols::models::models::Round` struct
export interface Round {
    duel_id: BigInt;
    round_number: Number;
    state: Number;
    shot_a: Shot;
    shot_b: Shot;
    
}

export const RoundDefinition = {
    duel_id: RecsType.BigInt,
    round_number: RecsType.Number,
    state: RecsType.Number,
    shot_a: ShotDefinition,
    shot_b: ShotDefinition,
    
};


// Type definition for `pistols::models::table::TTable` struct
export interface TTable {
    table_id: BigInt;
    description: BigInt;
    contract_address: BigInt;
    wager_min: U256;
    fee_min: U256;
    fee_pct: Number;
    is_open: Boolean;
    
}

export const TTableDefinition = {
    table_id: RecsType.BigInt,
    description: RecsType.BigInt,
    contract_address: RecsType.BigInt,
    wager_min: U256Definition,
    fee_min: U256Definition,
    fee_pct: RecsType.Number,
    is_open: RecsType.Boolean,
    
};


// Type definition for `pistols::models::models::Challenge` struct
export interface Challenge {
    duel_id: BigInt;
    duelist_a: BigInt;
    duelist_b: BigInt;
    message: BigInt;
    table_id: BigInt;
    state: Number;
    round_number: Number;
    winner: Number;
    timestamp_start: Number;
    timestamp_end: Number;
    
}

export const ChallengeDefinition = {
    duel_id: RecsType.BigInt,
    duelist_a: RecsType.BigInt,
    duelist_b: RecsType.BigInt,
    message: RecsType.BigInt,
    table_id: RecsType.BigInt,
    state: RecsType.Number,
    round_number: RecsType.Number,
    winner: RecsType.Number,
    timestamp_start: RecsType.Number,
    timestamp_end: RecsType.Number,
    
};


// Type definition for `pistols::models::models::Chances` struct
export interface Chances {
    key: BigInt;
    crit_chances: Number;
    crit_bonus: Number;
    hit_chances: Number;
    hit_bonus: Number;
    lethal_chances: Number;
    lethal_bonus: Number;
    
}

export const ChancesDefinition = {
    key: RecsType.BigInt,
    crit_chances: RecsType.Number,
    crit_bonus: RecsType.Number,
    hit_chances: RecsType.Number,
    hit_bonus: RecsType.Number,
    lethal_chances: RecsType.Number,
    lethal_bonus: RecsType.Number,
    
};


// Type definition for `pistols::models::models::Duelist` struct
export interface Duelist {
    address: BigInt;
    name: BigInt;
    profile_pic: Number;
    score: Score;
    timestamp: Number;
    
}

export const DuelistDefinition = {
    address: RecsType.BigInt,
    name: RecsType.BigInt,
    profile_pic: RecsType.Number,
    score: ScoreDefinition,
    timestamp: RecsType.Number,
    
};


// Type definition for `token::components::security::initializable::InitializableModel` struct
export interface InitializableModel {
    token: BigInt;
    initialized: Boolean;
    
}

export const InitializableModelDefinition = {
    token: RecsType.BigInt,
    initialized: RecsType.Boolean,
    
};


// Type definition for `token::components::token::erc20::erc20_metadata::ERC20MetadataModel` struct
export interface ERC20MetadataModel {
    token: BigInt;
    name: BigInt;
    symbol: BigInt;
    decimals: Number;
    total_supply: U256;
    
}

export const ERC20MetadataModelDefinition = {
    token: RecsType.BigInt,
    name: RecsType.BigInt,
    symbol: RecsType.BigInt,
    decimals: RecsType.Number,
    total_supply: U256Definition,
    
};


// Type definition for `token::components::token::erc20::erc20_balance::ERC20BalanceModel` struct
export interface ERC20BalanceModel {
    token: BigInt;
    account: BigInt;
    amount: U256;
    
}

export const ERC20BalanceModelDefinition = {
    token: RecsType.BigInt,
    account: RecsType.BigInt,
    amount: U256Definition,
    
};


// Type definition for `pistols::models::models::Snapshot` struct
export interface Snapshot {
    duel_id: BigInt;
    score_a: Score;
    score_b: Score;
    
}

export const SnapshotDefinition = {
    duel_id: RecsType.BigInt,
    score_a: ScoreDefinition,
    score_b: ScoreDefinition,
    
};


export function defineContractComponents(world: World) {
    return {

        // Model definition for `pistols::models::models::Wager` model
        Wager: (() => {
            return defineComponent(
                world,
                {
                    duel_id: RecsType.BigInt,
                    value: U256Definition,
                    fee: U256Definition,
                },
                {
                    metadata: {
                        name: "Wager",
                        types: ["u128"],
                        customTypes: ["U256", "U256"],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::models::Pact` model
        Pact: (() => {
            return defineComponent(
                world,
                {
                    pair: RecsType.BigInt,
                    duel_id: RecsType.BigInt,
                },
                {
                    metadata: {
                        name: "Pact",
                        types: ["u128", "u128"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::config::Config` model
        Config: (() => {
            return defineComponent(
                world,
                {
                    key: RecsType.Number,
                    initialized: RecsType.Boolean,
                    owner_address: RecsType.BigInt,
                    treasury_address: RecsType.BigInt,
                    paused: RecsType.Boolean,
                },
                {
                    metadata: {
                        name: "Config",
                        types: ["u8", "bool", "ContractAddress", "ContractAddress", "bool"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::models::Scoreboard` model
        Scoreboard: (() => {
            return defineComponent(
                world,
                {
                    address: RecsType.BigInt,
                    table_id: RecsType.BigInt,
                    score: ScoreDefinition,
                    wager_won: U256Definition,
                    wager_lost: U256Definition,
                },
                {
                    metadata: {
                        name: "Scoreboard",
                        types: ["ContractAddress", "felt252"],
                        customTypes: ["Score", "U256", "U256"],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::models::Round` model
        Round: (() => {
            return defineComponent(
                world,
                {
                    duel_id: RecsType.BigInt,
                    round_number: RecsType.Number,
                    state: RecsType.Number,
                    shot_a: ShotDefinition,
                    shot_b: ShotDefinition,
                },
                {
                    metadata: {
                        name: "Round",
                        types: ["u128", "u8", "u8"],
                        customTypes: ["Shot", "Shot"],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::table::TTable` model
        TTable: (() => {
            return defineComponent(
                world,
                {
                    table_id: RecsType.BigInt,
                    description: RecsType.BigInt,
                    contract_address: RecsType.BigInt,
                    wager_min: U256Definition,
                    fee_min: U256Definition,
                    fee_pct: RecsType.Number,
                    is_open: RecsType.Boolean,
                },
                {
                    metadata: {
                        name: "TTable",
                        types: ["felt252", "felt252", "ContractAddress", "u8", "bool"],
                        customTypes: ["U256", "U256"],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::models::Challenge` model
        Challenge: (() => {
            return defineComponent(
                world,
                {
                    duel_id: RecsType.BigInt,
                    duelist_a: RecsType.BigInt,
                    duelist_b: RecsType.BigInt,
                    message: RecsType.BigInt,
                    table_id: RecsType.BigInt,
                    state: RecsType.Number,
                    round_number: RecsType.Number,
                    winner: RecsType.Number,
                    timestamp_start: RecsType.Number,
                    timestamp_end: RecsType.Number,
                },
                {
                    metadata: {
                        name: "Challenge",
                        types: ["u128", "ContractAddress", "ContractAddress", "felt252", "felt252", "u8", "u8", "u8", "u64", "u64"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::models::Chances` model
        Chances: (() => {
            return defineComponent(
                world,
                {
                    key: RecsType.BigInt,
                    crit_chances: RecsType.Number,
                    crit_bonus: RecsType.Number,
                    hit_chances: RecsType.Number,
                    hit_bonus: RecsType.Number,
                    lethal_chances: RecsType.Number,
                    lethal_bonus: RecsType.Number,
                },
                {
                    metadata: {
                        name: "Chances",
                        types: ["felt252", "u8", "u8", "u8", "u8", "u8", "u8"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::models::Duelist` model
        Duelist: (() => {
            return defineComponent(
                world,
                {
                    address: RecsType.BigInt,
                    name: RecsType.BigInt,
                    profile_pic: RecsType.Number,
                    score: ScoreDefinition,
                    timestamp: RecsType.Number,
                },
                {
                    metadata: {
                        name: "Duelist",
                        types: ["ContractAddress", "felt252", "u8", "u64"],
                        customTypes: ["Score"],
                    },
                }
            );
        })(),

        // Model definition for `token::components::security::initializable::InitializableModel` model
        InitializableModel: (() => {
            return defineComponent(
                world,
                {
                    token: RecsType.BigInt,
                    initialized: RecsType.Boolean,
                },
                {
                    metadata: {
                        name: "InitializableModel",
                        types: ["ContractAddress", "bool"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `pistols::models::models::Snapshot` model
        Snapshot: (() => {
            return defineComponent(
                world,
                {
                    duel_id: RecsType.BigInt,
                    score_a: ScoreDefinition,
                    score_b: ScoreDefinition,
                },
                {
                    metadata: {
                        name: "Snapshot",
                        types: ["u128"],
                        customTypes: ["Score", "Score"],
                    },
                }
            );
        })(),
    };
}
