[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x97b9dca8dd44989def68eea082b358ff81a7d7ae648ca2a3a8d0095db4e8a1"
transaction_hash = "0x5c2aae24c5fbcd0a2746b07ec217132d275fe53cecf611a4fd3fda1d60cda36"
block_number = 3
seed = "pistols"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x6c4d29225a32116a42d90f46ed556e431694cff41f5b3b68732e5c41aa01041"
class_hash = "0x5809efeb3c9c63821b16dc2e5656af7f951fb57ddd594c5281caddd65ce3d5c"
original_class_hash = "0x5809efeb3c9c63821b16dc2e5656af7f951fb57ddd594c5281caddd65ce3d5c"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-admin-36fd2037.json"
reads = []
writes = ["ns:pistols"]
init_calldata = [
    "0x0",
    "$contract_address:pistols-lords_mock",
]
tag = "pistols-admin"
systems = [
    "grant_admin",
    "set_config",
    "set_paused",
    "set_table",
    "set_table_admittance",
    "open_table",
]
manifest_name = "pistols-admin-36fd2037"

[[contracts]]
kind = "DojoContract"
address = "0x256d2d99999eaa89e20935b30b2f9dc8f6068082125b19328b7b4bcb05bef35"
class_hash = "0x35685bf9a02a4dbe997903784ad7479e0422895c57f9eacecbf48c37780ead9"
original_class_hash = "0x35685bf9a02a4dbe997903784ad7479e0422895c57f9eacecbf48c37780ead9"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-duelist-5e4878f0.json"
reads = []
writes = [
    "pistols-TokenConfig",
    "pistols-Duelist",
]
init_calldata = [
    "0x0",
    "0x0",
    "0x0",
    "$contract_address:pistols-lords_mock",
    "0",
]
tag = "pistols-duelist"
systems = ["delete_duelist"]
manifest_name = "pistols-duelist-5e4878f0"

[[contracts]]
kind = "DojoContract"
address = "0x489b4afb7caa5f267016313a07610c37a4ee26890b0c5b6bbd30e66baed2cc3"
class_hash = "0x420371bbbba4913976ec4b65fae926c097e2984dc7ae695d0a28f55e48d0003"
original_class_hash = "0x420371bbbba4913976ec4b65fae926c097e2984dc7ae695d0a28f55e48d0003"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-game-32c10283.json"
reads = []
writes = ["ns:pistols"]
init_calldata = []
tag = "pistols-game"
systems = [
    "commit_moves",
    "reveal_moves",
    "_emitDuelistRegisteredEvent",
    "_emitNewChallengeEvent",
    "_emitChallengeAcceptedEvent",
    "_emitPostRevealEvents",
    "_emitDuelistTurnEvent",
    "_emitChallengeResolvedEvent",
]
manifest_name = "pistols-game-32c10283"

[[contracts]]
kind = "DojoContract"
address = "0x7247545b8213348893a1e45b185fb6b5c591c7649d0040ac4f9e6949b348444"
class_hash = "0x25483853492c8ae171b14b3bde308fd7b0937abb80eace6183574d9175f050f"
original_class_hash = "0x25483853492c8ae171b14b3bde308fd7b0937abb80eace6183574d9175f050f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-lords_mock-2b1156e6.json"
reads = []
writes = ["pistols-CoinConfig"]
init_calldata = [
    "$contract_address:pistols-game",
    "10000000000000000000000",
]
tag = "pistols-lords_mock"
systems = [
    "faucet",
    "mint",
]
manifest_name = "pistols-lords_mock-2b1156e6"

[[contracts]]
kind = "DojoContract"
address = "0x7b9632f23d7191d04b6d7ac9f84728a644ef48d87b0f20be1c0a91db69663ed"
class_hash = "0x6a0d0ece6d37f67bb12d3cf9ec053b75d7862c28fa5e6c35f6a262efc17ab3d"
original_class_hash = "0x6a0d0ece6d37f67bb12d3cf9ec053b75d7862c28fa5e6c35f6a262efc17ab3d"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-rng-13f1a6a9.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-rng"
systems = []
manifest_name = "pistols-rng-13f1a6a9"

[[models]]
kind = "DojoModel"
class_hash = "0x621e8a8d75db58a04b11def09072b507b27ea956db4ea488d32741a7cd7aee3"
original_class_hash = "0x621e8a8d75db58a04b11def09072b507b27ea956db4ea488d32741a7cd7aee3"
abi = "manifests/dev/deployment/abis/models/pistols-Challenge-673267b6.json"
tag = "pistols-Challenge"
qualified_path = "pistols::models::challenge::challenge"
manifest_name = "pistols-Challenge-673267b6"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "table_id"
type = "felt252"
key = false

[[models.members]]
name = "premise"
type = "Premise"
key = false

[[models.members]]
name = "quote"
type = "felt252"
key = false

[[models.members]]
name = "address_a"
type = "ContractAddress"
key = false

[[models.members]]
name = "address_b"
type = "ContractAddress"
key = false

[[models.members]]
name = "duelist_id_a"
type = "u128"
key = false

[[models.members]]
name = "duelist_id_b"
type = "u128"
key = false

[[models.members]]
name = "state"
type = "ChallengeState"
key = false

[[models.members]]
name = "round_number"
type = "u8"
key = false

[[models.members]]
name = "winner"
type = "u8"
key = false

[[models.members]]
name = "timestamp_start"
type = "u64"
key = false

[[models.members]]
name = "timestamp_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5da2748b86cdc9a68ce089f7638b800ba10c506b513338002d6e828308f072b"
original_class_hash = "0x5da2748b86cdc9a68ce089f7638b800ba10c506b513338002d6e828308f072b"
abi = "manifests/dev/deployment/abis/models/pistols-CoinConfig-26fad4df.json"
tag = "pistols-CoinConfig"
qualified_path = "pistols::models::coin_config::coin_config"
manifest_name = "pistols-CoinConfig-26fad4df"

[[models.members]]
name = "coin_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "faucet_amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3cf74429df2fffde1ab90fa02f725ef06d7aaef35cdacd56ad65024714f3a7f"
original_class_hash = "0x3cf74429df2fffde1ab90fa02f725ef06d7aaef35cdacd56ad65024714f3a7f"
abi = "manifests/dev/deployment/abis/models/pistols-Config-60742fa7.json"
tag = "pistols-Config"
qualified_path = "pistols::models::config::config"
manifest_name = "pistols-Config-60742fa7"

[[models.members]]
name = "key"
type = "u8"
key = true

[[models.members]]
name = "treasury_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "is_paused"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x438678aed538eaeacb5395be5b5bf337c8b620492ab0f54b032756bc3c3bd85"
original_class_hash = "0x438678aed538eaeacb5395be5b5bf337c8b620492ab0f54b032756bc3c3bd85"
abi = "manifests/dev/deployment/abis/models/pistols-Duelist-1ec34ce9.json"
tag = "pistols-Duelist"
qualified_path = "pistols::models::duelist::duelist"
manifest_name = "pistols-Duelist-1ec34ce9"

[[models.members]]
name = "duelist_id"
type = "u128"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[models.members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "score"
type = "Score"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1742fb856890207335d9bbec53122aed0b5593b213298050eec50c4e86fcee9"
original_class_hash = "0x1742fb856890207335d9bbec53122aed0b5593b213298050eec50c4e86fcee9"
abi = "manifests/dev/deployment/abis/models/pistols-Pact-72a33a65.json"
tag = "pistols-Pact"
qualified_path = "pistols::models::duelist::pact"
manifest_name = "pistols-Pact-72a33a65"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "pair"
type = "u128"
key = true

[[models.members]]
name = "duel_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1f98abf30c3d96ae66e2816e354cc44c8c7553ceb1e3043909feca4eafa3755"
original_class_hash = "0x1f98abf30c3d96ae66e2816e354cc44c8c7553ceb1e3043909feca4eafa3755"
abi = "manifests/dev/deployment/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
qualified_path = "pistols::models::challenge::round"
manifest_name = "pistols-Round-617e0a3d"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "round_number"
type = "u8"
key = true

[[models.members]]
name = "moves_a"
type = "Moves"
key = false

[[models.members]]
name = "moves_b"
type = "Moves"
key = false

[[models.members]]
name = "state_a"
type = "DuelistState"
key = false

[[models.members]]
name = "state_b"
type = "DuelistState"
key = false

[[models.members]]
name = "state"
type = "RoundState"
key = false

[[models.members]]
name = "final_step"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x20217ebd369f280d7c38719ba769b9af22a3960fb0b230106c672daed0a1361"
original_class_hash = "0x20217ebd369f280d7c38719ba769b9af22a3960fb0b230106c672daed0a1361"
abi = "manifests/dev/deployment/abis/models/pistols-Scoreboard-18889906.json"
tag = "pistols-Scoreboard"
qualified_path = "pistols::models::duelist::scoreboard"
manifest_name = "pistols-Scoreboard-18889906"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "duelist_id"
type = "u128"
key = true

[[models.members]]
name = "score"
type = "Score"
key = false

[[models.members]]
name = "wager_won"
type = "u128"
key = false

[[models.members]]
name = "wager_lost"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71ec603d2893fa4e8573fb1c94e414124dc633b8c6b96dcc21ad8317fe2cf10"
original_class_hash = "0x71ec603d2893fa4e8573fb1c94e414124dc633b8c6b96dcc21ad8317fe2cf10"
abi = "manifests/dev/deployment/abis/models/pistols-TableAdmittance-1b01f43d.json"
tag = "pistols-TableAdmittance"
qualified_path = "pistols::models::table::table_admittance"
manifest_name = "pistols-TableAdmittance-1b01f43d"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "accounts"
type = "Array<ContractAddress>"
key = false

[[models.members]]
name = "duelists"
type = "Array<u128>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6b05e10a9a84fe260a91833936740b56b77a8caff0cd9fd842f4b6e0ec95ec5"
original_class_hash = "0x6b05e10a9a84fe260a91833936740b56b77a8caff0cd9fd842f4b6e0ec95ec5"
abi = "manifests/dev/deployment/abis/models/pistols-TableConfig-1e8368fc.json"
tag = "pistols-TableConfig"
qualified_path = "pistols::models::table::table_config"
manifest_name = "pistols-TableConfig-1e8368fc"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "description"
type = "felt252"
key = false

[[models.members]]
name = "table_type"
type = "TableType"
key = false

[[models.members]]
name = "deck_type"
type = "DeckType"
key = false

[[models.members]]
name = "fee_contract_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "fee_collector_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "fee_min"
type = "u128"
key = false

[[models.members]]
name = "is_open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e1138764631b591734bf457f5c46f56d5bd974c60fed8109c638a65848732a"
original_class_hash = "0x1e1138764631b591734bf457f5c46f56d5bd974c60fed8109c638a65848732a"
abi = "manifests/dev/deployment/abis/models/pistols-TableWager-2d819fd3.json"
tag = "pistols-TableWager"
qualified_path = "pistols::models::table::table_wager"
manifest_name = "pistols-TableWager-2d819fd3"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "wager_min"
type = "u128"
key = false

[[models.members]]
name = "wager_max"
type = "u128"
key = false

[[models.members]]
name = "fee_pct"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1993f8ce5ce075d71e202bbfdb8628afd7978d5ae9aed8345ee78d9dae57305"
original_class_hash = "0x1993f8ce5ce075d71e202bbfdb8628afd7978d5ae9aed8345ee78d9dae57305"
abi = "manifests/dev/deployment/abis/models/pistols-TokenConfig-56ebd338.json"
tag = "pistols-TokenConfig"
qualified_path = "pistols::models::token_config::token_config"
manifest_name = "pistols-TokenConfig-56ebd338"

[[models.members]]
name = "token_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "renderer_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "treasury_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "fee_contract"
type = "ContractAddress"
key = false

[[models.members]]
name = "fee_amount"
type = "u128"
key = false

[[models.members]]
name = "minted_count"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e5d78a5b7ad246855311ee7b34e441961d7d3c14331ea70c3f87eb120deed6"
original_class_hash = "0x1e5d78a5b7ad246855311ee7b34e441961d7d3c14331ea70c3f87eb120deed6"
abi = "manifests/dev/deployment/abis/models/pistols-Wager-4cd30873.json"
tag = "pistols-Wager"
qualified_path = "pistols::models::challenge::wager"
manifest_name = "pistols-Wager-4cd30873"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "value"
type = "u128"
key = false

[[models.members]]
name = "fee"
type = "u128"
key = false
