[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x97b9dca8dd44989def68eea082b358ff81a7d7ae648ca2a3a8d0095db4e8a1"
transaction_hash = "0x269cef4e372249b30528699a7c3db261fab5d3ec261f9339e264f9e7ad2957e"
block_number = 3
seed = "pistols"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x6c4d29225a32116a42d90f46ed556e431694cff41f5b3b68732e5c41aa01041"
class_hash = "0x2811fe3f8b436c8123a9ce4a1ce56fcb0e9651717eebb82ead30298aa33a8ba"
original_class_hash = "0x2811fe3f8b436c8123a9ce4a1ce56fcb0e9651717eebb82ead30298aa33a8ba"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-admin-36fd2037.json"
reads = []
writes = ["ns:pistols"]
init_calldata = [
    "0x0",
    "$contract_address:pistols-lords_mock",
]
tag = "pistols-admin"
systems = [
    "grant_admin",
    "set_config",
    "set_paused",
    "set_table",
    "set_table_admittance",
    "open_table",
]
manifest_name = "pistols-admin-36fd2037"

[[contracts]]
kind = "DojoContract"
address = "0x3723324be73d95d56524f0e4a80a997edc2428d6f972b95b012010f06530af6"
class_hash = "0x5fc6d8de911ddf576bf581b822b64a9156a223740c04ec32af633017951c6b1"
original_class_hash = "0x5fc6d8de911ddf576bf581b822b64a9156a223740c04ec32af633017951c6b1"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-bank-7a683ab6.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-bank"
systems = ["charge"]
manifest_name = "pistols-bank-7a683ab6"

[[contracts]]
kind = "DojoContract"
address = "0x3db7f788e6cd2b6e18911da108a0f161a963c367ea953d916aa5d664c64fff2"
class_hash = "0x518a7ae9436541c488720c4bb39b0711a5a068b6d88c3c3da555ff4840c1db9"
original_class_hash = "0x518a7ae9436541c488720c4bb39b0711a5a068b6d88c3c3da555ff4840c1db9"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-duel_token-670a5c67.json"
reads = []
writes = [
    "pistols-TokenConfig",
    "pistols-Payment",
    "pistols-Challenge",
    "pistols-Round",
    "pistols-Pact",
    "pistols-Scoreboard",
]
init_calldata = [
    "0",
    "0x0",
    "0x0",
    "0",
]
tag = "pistols-duel_token"
systems = ["delete_duel"]
manifest_name = "pistols-duel_token-670a5c67"

[[contracts]]
kind = "DojoContract"
address = "0x75c9d8eae61c368eda84bc2962b6b7a478136607f9a3f238c1680921b686b28"
class_hash = "0x4fe07935f6bde1eec37bce698dd1666ff7422e7427cecb5200fe02cedf542e8"
original_class_hash = "0x4fe07935f6bde1eec37bce698dd1666ff7422e7427cecb5200fe02cedf542e8"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-duelist_token-45c96d20.json"
reads = []
writes = [
    "pistols-TokenConfig",
    "pistols-Payment",
    "pistols-Duelist",
]
init_calldata = [
    "0",
    "0x0",
    "0x0",
    "100000000000000000000",
]
tag = "pistols-duelist_token"
systems = ["delete_duelist"]
manifest_name = "pistols-duelist_token-45c96d20"

[[contracts]]
kind = "DojoContract"
address = "0x489b4afb7caa5f267016313a07610c37a4ee26890b0c5b6bbd30e66baed2cc3"
class_hash = "0x4084cb8957fdbadcb5d3926e862809d721b88a55edf5dc28059e0f8f9c50cd1"
original_class_hash = "0x4084cb8957fdbadcb5d3926e862809d721b88a55edf5dc28059e0f8f9c50cd1"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-game-32c10283.json"
reads = []
writes = ["ns:pistols"]
init_calldata = []
tag = "pistols-game"
systems = [
    "commit_moves",
    "reveal_moves",
]
manifest_name = "pistols-game-32c10283"

[[contracts]]
kind = "DojoContract"
address = "0x7247545b8213348893a1e45b185fb6b5c591c7649d0040ac4f9e6949b348444"
class_hash = "0x319d5f823cfdf61ef8a9520399f64d8efca886552064bc23e22eb0e3cd9792a"
original_class_hash = "0x319d5f823cfdf61ef8a9520399f64d8efca886552064bc23e22eb0e3cd9792a"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-lords_mock-2b1156e6.json"
reads = []
writes = ["pistols-CoinConfig"]
init_calldata = [
    "0x0",
    "10000000000000000000000",
]
tag = "pistols-lords_mock"
systems = [
    "faucet",
    "mint",
]
manifest_name = "pistols-lords_mock-2b1156e6"

[[contracts]]
kind = "DojoContract"
address = "0x7b9632f23d7191d04b6d7ac9f84728a644ef48d87b0f20be1c0a91db69663ed"
class_hash = "0x6a0d0ece6d37f67bb12d3cf9ec053b75d7862c28fa5e6c35f6a262efc17ab3d"
original_class_hash = "0x6a0d0ece6d37f67bb12d3cf9ec053b75d7862c28fa5e6c35f6a262efc17ab3d"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols-rng-13f1a6a9.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-rng"
systems = []
manifest_name = "pistols-rng-13f1a6a9"

[[models]]
kind = "DojoModel"
class_hash = "0x6aed17809106727dcf825292fd56ae40aea878d940c5f2f41f8f0bee14c8d52"
original_class_hash = "0x6aed17809106727dcf825292fd56ae40aea878d940c5f2f41f8f0bee14c8d52"
abi = "manifests/dev/deployment/abis/models/pistols-Challenge-673267b6.json"
tag = "pistols-Challenge"
qualified_path = "pistols::models::challenge::challenge"
manifest_name = "pistols-Challenge-673267b6"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models.members]]
name = "table_id"
type = "felt252"
key = false

[[models.members]]
name = "premise"
type = "Premise"
key = false

[[models.members]]
name = "quote"
type = "felt252"
key = false

[[models.members]]
name = "address_a"
type = "ContractAddress"
key = false

[[models.members]]
name = "address_b"
type = "ContractAddress"
key = false

[[models.members]]
name = "duelist_id_a"
type = "u128"
key = false

[[models.members]]
name = "duelist_id_b"
type = "u128"
key = false

[[models.members]]
name = "state"
type = "ChallengeState"
key = false

[[models.members]]
name = "winner"
type = "u8"
key = false

[[models.members]]
name = "timestamp_start"
type = "u64"
key = false

[[models.members]]
name = "timestamp_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3ad591c8b7ab3eaea8f9dc836dba3983bf9bc64c06f547af762ef63c0b34a7b"
original_class_hash = "0x3ad591c8b7ab3eaea8f9dc836dba3983bf9bc64c06f547af762ef63c0b34a7b"
abi = "manifests/dev/deployment/abis/models/pistols-CoinConfig-26fad4df.json"
tag = "pistols-CoinConfig"
qualified_path = "pistols::models::config::coin_config"
manifest_name = "pistols-CoinConfig-26fad4df"

[[models.members]]
name = "coin_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "faucet_amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x455693b12089abe5115f79996488498e282840dcb92a37e218aaf35c6cb308"
original_class_hash = "0x455693b12089abe5115f79996488498e282840dcb92a37e218aaf35c6cb308"
abi = "manifests/dev/deployment/abis/models/pistols-Config-60742fa7.json"
tag = "pistols-Config"
qualified_path = "pistols::models::config::config"
manifest_name = "pistols-Config-60742fa7"

[[models.members]]
name = "key"
type = "u8"
key = true

[[models.members]]
name = "treasury_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "lords_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "is_paused"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x396471c4a5237699b94c77a748ca7afb66587ec19d440c36a8a91bdc6c44c6b"
original_class_hash = "0x396471c4a5237699b94c77a748ca7afb66587ec19d440c36a8a91bdc6c44c6b"
abi = "manifests/dev/deployment/abis/models/pistols-Duelist-1ec34ce9.json"
tag = "pistols-Duelist"
qualified_path = "pistols::models::duelist::duelist"
manifest_name = "pistols-Duelist-1ec34ce9"

[[models.members]]
name = "duelist_id"
type = "u128"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[models.members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "score"
type = "Score"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1742fb856890207335d9bbec53122aed0b5593b213298050eec50c4e86fcee9"
original_class_hash = "0x1742fb856890207335d9bbec53122aed0b5593b213298050eec50c4e86fcee9"
abi = "manifests/dev/deployment/abis/models/pistols-Pact-72a33a65.json"
tag = "pistols-Pact"
qualified_path = "pistols::models::duelist::pact"
manifest_name = "pistols-Pact-72a33a65"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "pair"
type = "u128"
key = true

[[models.members]]
name = "duel_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x320046f9d54a87dd006b74503056c0f65ef9a24f045f49f74214853af986009"
original_class_hash = "0x320046f9d54a87dd006b74503056c0f65ef9a24f045f49f74214853af986009"
abi = "manifests/dev/deployment/abis/models/pistols-Payment-17a03e9c.json"
tag = "pistols-Payment"
qualified_path = "pistols::models::payment::payment"
manifest_name = "pistols-Payment-17a03e9c"

[[models.members]]
name = "key"
type = "felt252"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models.members]]
name = "client_percent"
type = "u8"
key = false

[[models.members]]
name = "ranking_percent"
type = "u8"
key = false

[[models.members]]
name = "owner_percent"
type = "u8"
key = false

[[models.members]]
name = "pool_percent"
type = "u8"
key = false

[[models.members]]
name = "treasury_percent"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3067e5ef04e89462955c15dc6e29f10f28d95ba01c720fa065a14c0782d26d6"
original_class_hash = "0x3067e5ef04e89462955c15dc6e29f10f28d95ba01c720fa065a14c0782d26d6"
abi = "manifests/dev/deployment/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
qualified_path = "pistols::models::challenge::round"
manifest_name = "pistols-Round-617e0a3d"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "moves_a"
type = "Moves"
key = false

[[models.members]]
name = "moves_b"
type = "Moves"
key = false

[[models.members]]
name = "state_a"
type = "DuelistState"
key = false

[[models.members]]
name = "state_b"
type = "DuelistState"
key = false

[[models.members]]
name = "state"
type = "RoundState"
key = false

[[models.members]]
name = "final_blow"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x795ea9ad88e1509713368089eef4ff54071c4da5d9098bc4b9ab59acd67cc6c"
original_class_hash = "0x795ea9ad88e1509713368089eef4ff54071c4da5d9098bc4b9ab59acd67cc6c"
abi = "manifests/dev/deployment/abis/models/pistols-Scoreboard-18889906.json"
tag = "pistols-Scoreboard"
qualified_path = "pistols::models::duelist::scoreboard"
manifest_name = "pistols-Scoreboard-18889906"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "duelist_id"
type = "u128"
key = true

[[models.members]]
name = "score"
type = "Score"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71ec603d2893fa4e8573fb1c94e414124dc633b8c6b96dcc21ad8317fe2cf10"
original_class_hash = "0x71ec603d2893fa4e8573fb1c94e414124dc633b8c6b96dcc21ad8317fe2cf10"
abi = "manifests/dev/deployment/abis/models/pistols-TableAdmittance-1b01f43d.json"
tag = "pistols-TableAdmittance"
qualified_path = "pistols::models::table::table_admittance"
manifest_name = "pistols-TableAdmittance-1b01f43d"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "accounts"
type = "Array<ContractAddress>"
key = false

[[models.members]]
name = "duelists"
type = "Array<u128>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3b41b2889a7b016ed6f0b3c30752219ac4c688aa28a245ec81afb0fa48eda73"
original_class_hash = "0x3b41b2889a7b016ed6f0b3c30752219ac4c688aa28a245ec81afb0fa48eda73"
abi = "manifests/dev/deployment/abis/models/pistols-TableConfig-1e8368fc.json"
tag = "pistols-TableConfig"
qualified_path = "pistols::models::table::table_config"
manifest_name = "pistols-TableConfig-1e8368fc"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "description"
type = "felt252"
key = false

[[models.members]]
name = "table_type"
type = "TableType"
key = false

[[models.members]]
name = "deck_type"
type = "DeckType"
key = false

[[models.members]]
name = "fee_collector_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "fee_min"
type = "u128"
key = false

[[models.members]]
name = "is_open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xf3b9a575856c67ef4eb4cdf6ec715118d21f119907e14672f28ee66748d9e8"
original_class_hash = "0xf3b9a575856c67ef4eb4cdf6ec715118d21f119907e14672f28ee66748d9e8"
abi = "manifests/dev/deployment/abis/models/pistols-TokenConfig-56ebd338.json"
tag = "pistols-TokenConfig"
qualified_path = "pistols::models::config::token_config"
manifest_name = "pistols-TokenConfig-56ebd338"

[[models.members]]
name = "token_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "renderer_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "minted_count"
type = "u128"
key = false
