kind = "DojoModel"
class_hash = "0x301ceb1e325561b80a7c8b49e71b09b062f79f0075a1d46ce00697db24771d2"
original_class_hash = "0x301ceb1e325561b80a7c8b49e71b09b062f79f0075a1d46ce00697db24771d2"
abi = "manifests/slot/base/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
manifest_name = "pistols-Round-617e0a3d"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "state"
type = "RoundState"
key = false

[[members]]
name = "shot_a"
type = "Shot"
key = false

[[members]]
name = "shot_b"
type = "Shot"
key = false
