kind = "DojoModel"
class_hash = "0x506b155f8dbf1bf15943979cba5d883571d973cbab16deae21d50bb952f6dd5"
original_class_hash = "0x506b155f8dbf1bf15943979cba5d883571d973cbab16deae21d50bb952f6dd5"
abi = "manifests/slot/abis/base/models/pistols_models_table_table_admittance.json"
name = "pistols::models::table::table_admittance"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "account_a"
type = "ContractAddress"
key = false

[[members]]
name = "account_b"
type = "ContractAddress"
key = false
