kind = "DojoModel"
class_hash = "0x6161137dd65989ef77fa903b18895bf776defd169795d92d04002d6dec81906"
original_class_hash = "0x6161137dd65989ef77fa903b18895bf776defd169795d92d04002d6dec81906"
abi = "manifests/slot/abis/base/models/pistols_models_challenge_round.json"
name = "pistols::models::challenge::round"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "state"
type = "u8"
key = false

[[members]]
name = "shot_a"
type = "Shot"
key = false

[[members]]
name = "shot_b"
type = "Shot"
key = false
