kind = "DojoModel"
class_hash = "0x736e03785d94cf63c151e7bcba309addecad18bfb8434d3cd277c0fc6a6cf34"
original_class_hash = "0x736e03785d94cf63c151e7bcba309addecad18bfb8434d3cd277c0fc6a6cf34"
abi = "manifests/slot/abis/base/models/pistols_models_duelist_pact.json"
name = "pistols::models::duelist::pact"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "pair"
type = "u128"
key = true

[[members]]
name = "duel_id"
type = "u128"
key = false
