kind = "DojoModel"
class_hash = "0x6774b0dcc9a4ebb62e6f42b70ebd46cd77387e8d71cc8e57dee1403feec298"
original_class_hash = "0x6774b0dcc9a4ebb62e6f42b70ebd46cd77387e8d71cc8e57dee1403feec298"
abi = "manifests/slot/base/abis/models/pistols-TableConfig-1e8368fc.json"
tag = "pistols-TableConfig"
qualified_path = "pistols::models::table::table_config"
manifest_name = "pistols-TableConfig-1e8368fc"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "table_type"
type = "TableType"
key = false

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "fee_collector_address"
type = "ContractAddress"
key = false

[[members]]
name = "wager_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "wager_min"
type = "u128"
key = false

[[members]]
name = "fee_min"
type = "u128"
key = false

[[members]]
name = "fee_pct"
type = "u8"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
