kind = "DojoModel"
class_hash = "0x1742fb856890207335d9bbec53122aed0b5593b213298050eec50c4e86fcee9"
original_class_hash = "0x1742fb856890207335d9bbec53122aed0b5593b213298050eec50c4e86fcee9"
abi = "manifests/slot/base/abis/models/pistols-Pact-72a33a65.json"
tag = "pistols-Pact"
manifest_name = "pistols-Pact-72a33a65"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "pair"
type = "u128"
key = true

[[members]]
name = "duel_id"
type = "u128"
key = false
