kind = "DojoModel"
class_hash = "0x1e5d78a5b7ad246855311ee7b34e441961d7d3c14331ea70c3f87eb120deed6"
original_class_hash = "0x1e5d78a5b7ad246855311ee7b34e441961d7d3c14331ea70c3f87eb120deed6"
abi = "manifests/slot/base/abis/models/pistols-Wager-4cd30873.json"
tag = "pistols-Wager"
manifest_name = "pistols-Wager-4cd30873"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "value"
type = "u128"
key = false

[[members]]
name = "fee"
type = "u128"
key = false
