kind = "DojoModel"
class_hash = "0x34a6018f441f3d5921a1d75bde251034179d2b9387a37af92011f9396b72672"
original_class_hash = "0x34a6018f441f3d5921a1d75bde251034179d2b9387a37af92011f9396b72672"
abi = "manifests/slot/abis/base/models/token_components_token_erc20_erc20_bridgeable_erc_20_bridgeable_model.json"
name = "token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false
