kind = "DojoModel"
class_hash = "0x1e44c64b3fe31a10c990df6329b3b37c49e35c34ab8c72a77b2f97dc57a4d67"
original_class_hash = "0x1e44c64b3fe31a10c990df6329b3b37c49e35c34ab8c72a77b2f97dc57a4d67"
abi = "manifests/slot/abis/base/models/token_components_token_erc721_erc721_balance_erc_721_balance_model.json"
name = "token::components::token::erc721::erc721_balance::erc_721_balance_model"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "account"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
