kind = "DojoModel"
class_hash = "0x438678aed538eaeacb5395be5b5bf337c8b620492ab0f54b032756bc3c3bd85"
original_class_hash = "0x438678aed538eaeacb5395be5b5bf337c8b620492ab0f54b032756bc3c3bd85"
abi = "manifests/sepolia/base/abis/models/pistols-Duelist-1ec34ce9.json"
tag = "pistols-Duelist"
qualified_path = "pistols::models::duelist::duelist"
manifest_name = "pistols-Duelist-1ec34ce9"

[[members]]
name = "duelist_id"
type = "u128"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "score"
type = "Score"
key = false
