kind = "DojoModel"
class_hash = "0x7eff05f9ab0d08e0894369ceb804a00c87c2dce4cc06ab857a1489113cb93ad"
original_class_hash = "0x7eff05f9ab0d08e0894369ceb804a00c87c2dce4cc06ab857a1489113cb93ad"
abi = "manifests/dev/base/abis/models/origami_token-ERC721OperatorApprovalModel-1083d4d1.json"
tag = "origami_token-ERC721OperatorApprovalModel"
manifest_name = "origami_token-ERC721OperatorApprovalModel-1083d4d1"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "operator"
type = "ContractAddress"
key = true

[[members]]
name = "approved"
type = "bool"
key = false
