kind = "DojoModel"
class_hash = "0xadec2dd1b121aa6105764a31f63a72103a57bca5603bfc95684c841812811a"
original_class_hash = "0xadec2dd1b121aa6105764a31f63a72103a57bca5603bfc95684c841812811a"
abi = "manifests/dev/base/abis/models/origami_token-ERC20BridgeableModel-28075fe4.json"
tag = "origami_token-ERC20BridgeableModel"
manifest_name = "origami_token-ERC20BridgeableModel-28075fe4"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false
