kind = "DojoModel"
class_hash = "0x2076eb50975ed3d1c7ef7198f8625139b6e89b18f8c398972fafb0291c4f03c"
original_class_hash = "0x2076eb50975ed3d1c7ef7198f8625139b6e89b18f8c398972fafb0291c4f03c"
abi = "manifests/dev/base/abis/models/origami_token-ERC20AllowanceModel-4fcf1991.json"
tag = "origami_token-ERC20AllowanceModel"
manifest_name = "origami_token-ERC20AllowanceModel-4fcf1991"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "spender"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
