kind = "DojoModel"
class_hash = "0x54e3569efebd2964afe0f7550a2b8980e8195baa25450e2f67a981079a75ffc"
original_class_hash = "0x54e3569efebd2964afe0f7550a2b8980e8195baa25450e2f67a981079a75ffc"
abi = "manifests/dev/base/abis/models/pistols-TableAdmittance-1b01f43d.json"
tag = "pistols-TableAdmittance"
manifest_name = "pistols-TableAdmittance-1b01f43d"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "accounts"
type = "Array<ContractAddress>"
key = false

[[members]]
name = "duelists"
type = "Array<u128>"
key = false
