kind = "DojoModel"
class_hash = "0x3ad591c8b7ab3eaea8f9dc836dba3983bf9bc64c06f547af762ef63c0b34a7b"
original_class_hash = "0x3ad591c8b7ab3eaea8f9dc836dba3983bf9bc64c06f547af762ef63c0b34a7b"
abi = "manifests/dev/base/abis/models/pistols-CoinConfig-26fad4df.json"
tag = "pistols-CoinConfig"
qualified_path = "pistols::models::config::coin_config"
manifest_name = "pistols-CoinConfig-26fad4df"

[[members]]
name = "coin_address"
type = "ContractAddress"
key = true

[[members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[members]]
name = "faucet_amount"
type = "u128"
key = false
