kind = "DojoModel"
class_hash = "0x3067e5ef04e89462955c15dc6e29f10f28d95ba01c720fa065a14c0782d26d6"
original_class_hash = "0x3067e5ef04e89462955c15dc6e29f10f28d95ba01c720fa065a14c0782d26d6"
abi = "manifests/dev/base/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
qualified_path = "pistols::models::challenge::round"
manifest_name = "pistols-Round-617e0a3d"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "moves_a"
type = "Moves"
key = false

[[members]]
name = "moves_b"
type = "Moves"
key = false

[[members]]
name = "state_a"
type = "DuelistState"
key = false

[[members]]
name = "state_b"
type = "DuelistState"
key = false

[[members]]
name = "state"
type = "RoundState"
key = false

[[members]]
name = "final_blow"
type = "felt252"
key = false
