kind = "DojoModel"
class_hash = "0x52c44b80c19c1bdce6c3aa5317d544356d3b92ed85b147313d129bf05f7d013"
original_class_hash = "0x52c44b80c19c1bdce6c3aa5317d544356d3b92ed85b147313d129bf05f7d013"
abi = "manifests/dev/base/abis/models/pistols-Duelist-1ec34ce9.json"
tag = "pistols-Duelist"
qualified_path = "pistols::models::duelist::duelist"
manifest_name = "pistols-Duelist-1ec34ce9"

[[members]]
name = "duelist_id"
type = "u128"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "score"
type = "Score"
key = false
