kind = "DojoModel"
class_hash = "0x5382c409bb4fd7cb00788d52be823c7250f713c36ae9bdf5577bf879307d104"
original_class_hash = "0x5382c409bb4fd7cb00788d52be823c7250f713c36ae9bdf5577bf879307d104"
abi = "manifests/dev/abis/base/models/pistols_models_challenge_snapshot.json"
name = "pistols::models::challenge::snapshot"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "score_a"
type = "Score"
key = false

[[members]]
name = "score_b"
type = "Score"
key = false
