kind = "DojoModel"
class_hash = "0x6b416c5ac7ad1dad71849ec5fa279e08b78a9ad8a45ffe0832f8dff6888bdc1"
original_class_hash = "0x6b416c5ac7ad1dad71849ec5fa279e08b78a9ad8a45ffe0832f8dff6888bdc1"
abi = "manifests/dev/abis/base/models/pistols_models_config_config.json"
name = "pistols::models::config::config"

[[members]]
name = "key"
type = "u8"
key = true

[[members]]
name = "initialized"
type = "bool"
key = false

[[members]]
name = "owner_address"
type = "ContractAddress"
key = false

[[members]]
name = "treasury_address"
type = "ContractAddress"
key = false

[[members]]
name = "duelists_address"
type = "ContractAddress"
key = false

[[members]]
name = "paused"
type = "bool"
key = false
