kind = "DojoModel"
class_hash = "0x1866f3ea11fcce3f9cbd98c6a7b51c205d4957a599c01e906bd92b5b0bc31bb"
original_class_hash = "0x1866f3ea11fcce3f9cbd98c6a7b51c205d4957a599c01e906bd92b5b0bc31bb"
abi = "manifests/dev/abis/base/models/pistols_models_duelist_duelist.json"
name = "pistols::models::duelist::duelist"

[[members]]
name = "duelist_id"
type = "u128"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "profile_pic_uri"
type = "ByteArray"
key = false

[[members]]
name = "profile_pic_type"
type = "u8"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "score"
type = "Score"
key = false
