kind = "DojoModel"
class_hash = "0x5a0e21f8cad43b6679931f00416be00635fd39b969ee4107ad764e9c474bb8f"
original_class_hash = "0x5a0e21f8cad43b6679931f00416be00635fd39b969ee4107ad764e9c474bb8f"
abi = "manifests/dev/abis/base/models/pistols_models_table_table_admittance.json"
name = "pistols::models::table::table_admittance"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "accounts"
type = "Array<ContractAddress>"
key = false

[[members]]
name = "duelists"
type = "Array<u128>"
key = false
