kind = "DojoModel"
class_hash = "0x3f3036a4faf363d133ace87f3bf0c5e615a542fa0aec5736ff73aef93984f16"
original_class_hash = "0x3f3036a4faf363d133ace87f3bf0c5e615a542fa0aec5736ff73aef93984f16"
abi = "manifests/dev/abis/base/models/pistols_models_table_table_config.json"
name = "pistols::models::table::table_config"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "table_type"
type = "TableType"
key = false

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "fee_collector_address"
type = "ContractAddress"
key = false

[[members]]
name = "wager_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "wager_min"
type = "u128"
key = false

[[members]]
name = "fee_min"
type = "u128"
key = false

[[members]]
name = "fee_pct"
type = "u8"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
