kind = "DojoModel"
class_hash = "0xb29578d4f1c86f529249c7694fb16c8558bdd732165280fb4217e06ded39fe"
original_class_hash = "0xb29578d4f1c86f529249c7694fb16c8558bdd732165280fb4217e06ded39fe"
abi = "manifests/dev/base/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
qualified_path = "pistols::models::challenge::round"
manifest_name = "pistols-Round-617e0a3d"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "moves_a"
type = "Moves"
key = false

[[members]]
name = "moves_b"
type = "Moves"
key = false

[[members]]
name = "state_a"
type = "DuelistState"
key = false

[[members]]
name = "state_b"
type = "DuelistState"
key = false

[[members]]
name = "state"
type = "RoundState"
key = false

[[members]]
name = "final_blow"
type = "felt252"
key = false
