kind = "DojoModel"
class_hash = "0xdb042e64740a8da91d86f231401f8ec6039dbe39fa6b2e601013184cf69f5a"
original_class_hash = "0xdb042e64740a8da91d86f231401f8ec6039dbe39fa6b2e601013184cf69f5a"
abi = "manifests/dev/abis/base/models/pistols_models_challenge_wager.json"
name = "pistols::models::challenge::wager"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "value"
type = "u128"
key = false

[[members]]
name = "fee"
type = "u128"
key = false
