kind = "DojoModel"
class_hash = "0x455693b12089abe5115f79996488498e282840dcb92a37e218aaf35c6cb308"
original_class_hash = "0x455693b12089abe5115f79996488498e282840dcb92a37e218aaf35c6cb308"
abi = "manifests/dev/base/abis/models/pistols-Config-60742fa7.json"
tag = "pistols-Config"
qualified_path = "pistols::models::config::config"
manifest_name = "pistols-Config-60742fa7"

[[members]]
name = "key"
type = "u8"
key = true

[[members]]
name = "treasury_address"
type = "ContractAddress"
key = false

[[members]]
name = "lords_address"
type = "ContractAddress"
key = false

[[members]]
name = "is_paused"
type = "bool"
key = false
