kind = "DojoModel"
class_hash = "0x263b1937ecd58448c77c5d1eb500eff83422c5dd65aecd350ab76e8e221c0d4"
original_class_hash = "0x263b1937ecd58448c77c5d1eb500eff83422c5dd65aecd350ab76e8e221c0d4"
abi = "manifests/dev/abis/base/models/pistols_models_table_table_config.json"
name = "pistols::models::table::table_config"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "wager_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "wager_min"
type = "u256"
key = false

[[members]]
name = "fee_min"
type = "u256"
key = false

[[members]]
name = "fee_pct"
type = "u8"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false

[[members]]
name = "table_type"
type = "TableType"
key = false
