kind = "DojoModel"
class_hash = "0x6b89e5b8d5b269d100e9d7c5533371c16079b3a492cdc539f87cb31c2b1d465"
original_class_hash = "0x6b89e5b8d5b269d100e9d7c5533371c16079b3a492cdc539f87cb31c2b1d465"
abi = "manifests/dev/abis/base/models/pistols_models_challenge_round.json"
name = "pistols::models::challenge::round"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "state"
type = "u8"
key = false

[[members]]
name = "shot_a"
type = "Shot"
key = false

[[members]]
name = "shot_b"
type = "Shot"
key = false
