kind = "DojoModel"
class_hash = "0x4a9bb942ed2cb6a594ecc67694f696e7b6282b0d9aa0714d56da03030a5373b"
original_class_hash = "0x4a9bb942ed2cb6a594ecc67694f696e7b6282b0d9aa0714d56da03030a5373b"
abi = "manifests/dev/base/abis/models/pistols-TokenBoundAddress-51e7eddb.json"
tag = "pistols-TokenBoundAddress"
qualified_path = "pistols::systems::components::token_bound::token_bound_address"
manifest_name = "pistols-TokenBoundAddress-51e7eddb"

[[members]]
name = "recipient"
type = "ContractAddress"
key = true

[[members]]
name = "contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "token_id"
type = "u128"
key = false
