kind = "DojoModel"
class_hash = "0x17e1babdde18196b7147165c157ca231b5bab7edae757d588a442b7c9d5ee87"
original_class_hash = "0x17e1babdde18196b7147165c157ca231b5bab7edae757d588a442b7c9d5ee87"
abi = "manifests/dev/abis/base/models/pistols_models_challenge_snapshot.json"
name = "pistols::models::challenge::snapshot"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "score_a"
type = "Score"
key = false

[[members]]
name = "score_b"
type = "Score"
key = false
