kind = "DojoModel"
class_hash = "0x1993f8ce5ce075d71e202bbfdb8628afd7978d5ae9aed8345ee78d9dae57305"
original_class_hash = "0x1993f8ce5ce075d71e202bbfdb8628afd7978d5ae9aed8345ee78d9dae57305"
abi = "manifests/dev/base/abis/models/pistols-TokenConfig-56ebd338.json"
tag = "pistols-TokenConfig"
qualified_path = "pistols::models::token_config::token_config"
manifest_name = "pistols-TokenConfig-56ebd338"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[members]]
name = "renderer_address"
type = "ContractAddress"
key = false

[[members]]
name = "treasury_address"
type = "ContractAddress"
key = false

[[members]]
name = "fee_contract"
type = "ContractAddress"
key = false

[[members]]
name = "fee_amount"
type = "u128"
key = false

[[members]]
name = "minted_count"
type = "u128"
key = false
