kind = "DojoModel"
class_hash = "0x6f3e4d09b1410dfcc3b5d63c79d84b2d261a37e30337ad8e8186fde784bcae7"
original_class_hash = "0x6f3e4d09b1410dfcc3b5d63c79d84b2d261a37e30337ad8e8186fde784bcae7"
abi = "manifests/dev/abis/base/models/pistols_models_duelist_scoreboard.json"
name = "pistols::models::duelist::scoreboard"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "duelist_id"
type = "u128"
key = true

[[members]]
name = "score"
type = "Score"
key = false

[[members]]
name = "wager_won"
type = "u256"
key = false

[[members]]
name = "wager_lost"
type = "u256"
key = false
