kind = "DojoModel"
class_hash = "0x77429cbea916a564e7ed25b5175ebb6bbdcf90e9da8aeb89b729f7e5b2a1d4f"
original_class_hash = "0x77429cbea916a564e7ed25b5175ebb6bbdcf90e9da8aeb89b729f7e5b2a1d4f"
abi = "manifests/dev/abis/base/models/pistols_models_duelist_scoreboard.json"
name = "pistols::models::duelist::scoreboard"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "duelist_id"
type = "u128"
key = true

[[members]]
name = "score"
type = "Score"
key = false

[[members]]
name = "wager_won"
type = "u256"
key = false

[[members]]
name = "wager_lost"
type = "u256"
key = false
