kind = "DojoModel"
class_hash = "0x6aed17809106727dcf825292fd56ae40aea878d940c5f2f41f8f0bee14c8d52"
original_class_hash = "0x6aed17809106727dcf825292fd56ae40aea878d940c5f2f41f8f0bee14c8d52"
abi = "manifests/dev/base/abis/models/pistols-Challenge-673267b6.json"
tag = "pistols-Challenge"
qualified_path = "pistols::models::challenge::challenge"
manifest_name = "pistols-Challenge-673267b6"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "seed"
type = "u128"
key = false

[[members]]
name = "table_id"
type = "felt252"
key = false

[[members]]
name = "premise"
type = "Premise"
key = false

[[members]]
name = "quote"
type = "felt252"
key = false

[[members]]
name = "address_a"
type = "ContractAddress"
key = false

[[members]]
name = "address_b"
type = "ContractAddress"
key = false

[[members]]
name = "duelist_id_a"
type = "u128"
key = false

[[members]]
name = "duelist_id_b"
type = "u128"
key = false

[[members]]
name = "state"
type = "ChallengeState"
key = false

[[members]]
name = "winner"
type = "u8"
key = false

[[members]]
name = "timestamp_start"
type = "u64"
key = false

[[members]]
name = "timestamp_end"
type = "u64"
key = false
