kind = "DojoModel"
class_hash = "0xf3b9a575856c67ef4eb4cdf6ec715118d21f119907e14672f28ee66748d9e8"
original_class_hash = "0xf3b9a575856c67ef4eb4cdf6ec715118d21f119907e14672f28ee66748d9e8"
abi = "manifests/dev/base/abis/models/pistols-TokenConfig-56ebd338.json"
tag = "pistols-TokenConfig"
qualified_path = "pistols::models::config::token_config"
manifest_name = "pistols-TokenConfig-56ebd338"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[members]]
name = "renderer_address"
type = "ContractAddress"
key = false

[[members]]
name = "minted_count"
type = "u128"
key = false
