kind = "DojoModel"
class_hash = "0x2659b781469f378092758cb186b55141668bde6ed97751c8e2290be85190cda"
original_class_hash = "0x2659b781469f378092758cb186b55141668bde6ed97751c8e2290be85190cda"
abi = "manifests/dev/abis/base/models/token_components_token_erc721_erc721_enumerable_erc_721_enumerable_index_model.json"
name = "token::components::token::erc721::erc721_enumerable::erc_721_enumerable_index_model"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u128"
key = true

[[members]]
name = "token_id"
type = "u128"
key = false
