kind = "DojoModel"
class_hash = "0x96a2fd2dbffe7a83ab8720f1e3288dee356076ab7cfeaa917253597bdb7b8e"
original_class_hash = "0x96a2fd2dbffe7a83ab8720f1e3288dee356076ab7cfeaa917253597bdb7b8e"
abi = "manifests/dev/abis/base/models/token_components_token_erc721_erc721_metadata_erc_721_meta_model.json"
name = "token::components::token::erc721::erc721_metadata::erc_721_meta_model"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "symbol"
type = "ByteArray"
key = false

[[members]]
name = "base_uri"
type = "ByteArray"
key = false
