/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  Duel: (() => {
	    return defineComponent(
	      world,
	      { duelId: RecsType.BigInt, challenger: RecsType.BigInt, challenged: RecsType.BigInt, pass_code: RecsType.BigInt },
	      {
	        metadata: {
	          name: "Duel",
	          types: ["felt252","contractaddress","contractaddress","felt252"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Duelist: (() => {
	    return defineComponent(
	      world,
	      { address: RecsType.BigInt, name: RecsType.BigInt },
	      {
	        metadata: {
	          name: "Duelist",
	          types: ["contractaddress","felt252"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
  };
}
