/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  Challenge: (() => {
	    return defineComponent(
	      world,
	      { duel_id: RecsType.BigInt, duelist_a: RecsType.BigInt, duelist_b: RecsType.BigInt, message: RecsType.BigInt, state: RecsType.Number, round_number: RecsType.Number, winner: RecsType.Number, timestamp_start: RecsType.Number, timestamp_end: RecsType.Number },
	      {
	        metadata: {
	          name: "Challenge",
	          types: ["u128","contractaddress","contractaddress","felt252","u8","u8","u8","u64","u64"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Duelist: (() => {
	    return defineComponent(
	      world,
	      { address: RecsType.BigInt, name: RecsType.BigInt, profile_pic: RecsType.Number, total_duels: RecsType.Number, total_wins: RecsType.Number, total_losses: RecsType.Number, total_draws: RecsType.Number, total_honour: RecsType.Number, honour: RecsType.Number, timestamp: RecsType.Number },
	      {
	        metadata: {
	          name: "Duelist",
	          types: ["contractaddress","felt252","u8","u16","u16","u16","u16","u32","u8","u64"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Pact: (() => {
	    return defineComponent(
	      world,
	      { pair: RecsType.BigInt, duel_id: RecsType.BigInt },
	      {
	        metadata: {
	          name: "Pact",
	          types: ["u128","u128"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Round: (() => {
	    return defineComponent(
	      world,
	      { duel_id: RecsType.BigInt, round_number: RecsType.Number, state: RecsType.Number, shot_a: { hash: RecsType.Number, salt: RecsType.Number, action: RecsType.Number, chance_crit: RecsType.Number, chance_hit: RecsType.Number, dice_crit: RecsType.Number, dice_hit: RecsType.Number, damage: RecsType.Number, block: RecsType.Number, health: RecsType.Number, honour: RecsType.Number, win: RecsType.Number }, shot_b: { hash: RecsType.Number, salt: RecsType.Number, action: RecsType.Number, chance_crit: RecsType.Number, chance_hit: RecsType.Number, dice_crit: RecsType.Number, dice_hit: RecsType.Number, damage: RecsType.Number, block: RecsType.Number, health: RecsType.Number, honour: RecsType.Number, win: RecsType.Number } },
	      {
	        metadata: {
	          name: "Round",
	          types: ["u128","u8","u8","u64","u64","u16","u8","u8","u8","u8","u8","u8","u8","u8","u8","u64","u64","u16","u8","u8","u8","u8","u8","u8","u8","u8","u8"],
	          customTypes: ["Shot","Shot"],
	        },
	      }
	    );
	  })(),
  };
}
