tag = "pistols-actions"
writes = [
  "pistols-Duelist",
  "pistols-Scoreboard",
  "pistols-Challenge",
  "pistols-Snapshot",
  "pistols-Wager",
  "pistols-Pact",
  "pistols-Round",
]
init_calldata = []
