tag = "pistols-admin"
writes = [
  "pistols-Config",
  "pistols-TableConfig",
  "pistols-TableAdmittance",
]
init_calldata = [
  "0x0",  # treasury (or initializer)
  "$contract_address:pistols-lords_mock", # lords contract
]
