/* Autogenerated file. Do not edit manually. */
// from: ../../client/public/textures/cards

// import _textures_cards_card_back_png from "./encoded/_textures_cards_card_back_png"
import _textures_cards_card_circular_honourable_png from "./encoded/_textures_cards_card_circular_honourable_png"
import _textures_cards_card_circular_neutral_png from "./encoded/_textures_cards_card_circular_neutral_png"
import _textures_cards_card_circular_trickster_png from "./encoded/_textures_cards_card_circular_trickster_png"
import _textures_cards_card_circular_villainous_png from "./encoded/_textures_cards_card_circular_villainous_png"
import _textures_cards_card_disabled_png from "./encoded/_textures_cards_card_disabled_png"
// import _textures_cards_card_front_blue_png from "./encoded/_textures_cards_card_front_blue_png"
// import _textures_cards_card_front_brown_png from "./encoded/_textures_cards_card_front_brown_png"
// import _textures_cards_card_front_face_grim_png from "./encoded/_textures_cards_card_front_face_grim_png"
// import _textures_cards_card_front_face_png from "./encoded/_textures_cards_card_front_face_png"
// import _textures_cards_card_front_red_png from "./encoded/_textures_cards_card_front_red_png"
// import _textures_cards_card_front_shoot_png from "./encoded/_textures_cards_card_front_shoot_png"
// import _textures_cards_card_front_yellow_png from "./encoded/_textures_cards_card_front_yellow_png"
// import _textures_cards_card_wide_brown_png from "./encoded/_textures_cards_card_wide_brown_png"

export const assets = {
  // _textures_cards_card_back_png: _textures_cards_card_back_png,
  _textures_cards_card_circular_honourable_png: _textures_cards_card_circular_honourable_png,
  _textures_cards_card_circular_neutral_png: _textures_cards_card_circular_neutral_png,
  _textures_cards_card_circular_trickster_png: _textures_cards_card_circular_trickster_png,
  _textures_cards_card_circular_villainous_png: _textures_cards_card_circular_villainous_png,
  _textures_cards_card_disabled_png: _textures_cards_card_disabled_png,
  // _textures_cards_card_front_blue_png: _textures_cards_card_front_blue_png,
  // _textures_cards_card_front_brown_png: _textures_cards_card_front_brown_png,
  // _textures_cards_card_front_face_grim_png: _textures_cards_card_front_face_grim_png,
  // _textures_cards_card_front_face_png: _textures_cards_card_front_face_png,
  // _textures_cards_card_front_red_png: _textures_cards_card_front_red_png,
  // _textures_cards_card_front_shoot_png: _textures_cards_card_front_shoot_png,
  // _textures_cards_card_front_yellow_png: _textures_cards_card_front_yellow_png,
  // _textures_cards_card_wide_brown_png: _textures_cards_card_wide_brown_png,
}
