/* Autogenerated file. Do not edit manually. */
// from: ../../client/public/profiles

import _profiles_bots_00_jpg from "./encoded/_profiles_bots_00_jpg"
import _profiles_bots_01_jpg from "./encoded/_profiles_bots_01_jpg"
import _profiles_bots_02_jpg from "./encoded/_profiles_bots_02_jpg"
import _profiles_bots_03_jpg from "./encoded/_profiles_bots_03_jpg"
import _profiles_characters_00_jpg from "./encoded/_profiles_characters_00_jpg"
import _profiles_characters_01_jpg from "./encoded/_profiles_characters_01_jpg"
import _profiles_characters_02_jpg from "./encoded/_profiles_characters_02_jpg"
import _profiles_characters_03_jpg from "./encoded/_profiles_characters_03_jpg"
import _profiles_characters_04_jpg from "./encoded/_profiles_characters_04_jpg"
import _profiles_genesis_00_jpg from "./encoded/_profiles_genesis_00_jpg"
import _profiles_genesis_01_jpg from "./encoded/_profiles_genesis_01_jpg"
import _profiles_genesis_02_jpg from "./encoded/_profiles_genesis_02_jpg"
import _profiles_genesis_03_jpg from "./encoded/_profiles_genesis_03_jpg"
import _profiles_genesis_04_jpg from "./encoded/_profiles_genesis_04_jpg"
import _profiles_genesis_05_jpg from "./encoded/_profiles_genesis_05_jpg"
import _profiles_genesis_06_jpg from "./encoded/_profiles_genesis_06_jpg"
import _profiles_genesis_07_jpg from "./encoded/_profiles_genesis_07_jpg"
import _profiles_genesis_08_jpg from "./encoded/_profiles_genesis_08_jpg"
import _profiles_genesis_09_jpg from "./encoded/_profiles_genesis_09_jpg"
import _profiles_genesis_10_jpg from "./encoded/_profiles_genesis_10_jpg"
import _profiles_genesis_11_jpg from "./encoded/_profiles_genesis_11_jpg"
import _profiles_genesis_12_jpg from "./encoded/_profiles_genesis_12_jpg"
import _profiles_genesis_13_jpg from "./encoded/_profiles_genesis_13_jpg"
import _profiles_genesis_14_jpg from "./encoded/_profiles_genesis_14_jpg"
import _profiles_genesis_15_jpg from "./encoded/_profiles_genesis_15_jpg"
import _profiles_genesis_16_jpg from "./encoded/_profiles_genesis_16_jpg"
import _profiles_genesis_17_jpg from "./encoded/_profiles_genesis_17_jpg"
import _profiles_genesis_18_jpg from "./encoded/_profiles_genesis_18_jpg"
import _profiles_genesis_19_jpg from "./encoded/_profiles_genesis_19_jpg"
import _profiles_genesis_20_jpg from "./encoded/_profiles_genesis_20_jpg"
import _profiles_genesis_21_jpg from "./encoded/_profiles_genesis_21_jpg"
import _profiles_genesis_22_jpg from "./encoded/_profiles_genesis_22_jpg"
import _profiles_genesis_23_jpg from "./encoded/_profiles_genesis_23_jpg"
import _profiles_genesis_24_jpg from "./encoded/_profiles_genesis_24_jpg"
import _profiles_genesis_25_jpg from "./encoded/_profiles_genesis_25_jpg"
import _profiles_genesis_26_jpg from "./encoded/_profiles_genesis_26_jpg"
import _profiles_genesis_27_jpg from "./encoded/_profiles_genesis_27_jpg"
import _profiles_genesis_28_jpg from "./encoded/_profiles_genesis_28_jpg"
import _profiles_genesis_29_jpg from "./encoded/_profiles_genesis_29_jpg"
import _profiles_genesis_30_jpg from "./encoded/_profiles_genesis_30_jpg"
import _profiles_genesis_31_jpg from "./encoded/_profiles_genesis_31_jpg"
import _profiles_genesis_32_jpg from "./encoded/_profiles_genesis_32_jpg"
import _profiles_genesis_33_jpg from "./encoded/_profiles_genesis_33_jpg"
import _profiles_genesis_34_jpg from "./encoded/_profiles_genesis_34_jpg"
import _profiles_genesis_35_jpg from "./encoded/_profiles_genesis_35_jpg"
import _profiles_genesis_36_jpg from "./encoded/_profiles_genesis_36_jpg"
import _profiles_genesis_37_jpg from "./encoded/_profiles_genesis_37_jpg"
import _profiles_genesis_38_jpg from "./encoded/_profiles_genesis_38_jpg"
import _profiles_genesis_39_jpg from "./encoded/_profiles_genesis_39_jpg"
import _profiles_genesis_40_jpg from "./encoded/_profiles_genesis_40_jpg"
import _profiles_genesis_41_jpg from "./encoded/_profiles_genesis_41_jpg"
import _profiles_genesis_42_jpg from "./encoded/_profiles_genesis_42_jpg"
import _profiles_genesis_43_jpg from "./encoded/_profiles_genesis_43_jpg"
import _profiles_genesis_44_jpg from "./encoded/_profiles_genesis_44_jpg"
import _profiles_genesis_45_jpg from "./encoded/_profiles_genesis_45_jpg"
import _profiles_genesis_46_jpg from "./encoded/_profiles_genesis_46_jpg"
import _profiles_genesis_47_jpg from "./encoded/_profiles_genesis_47_jpg"
import _profiles_genesis_48_jpg from "./encoded/_profiles_genesis_48_jpg"
import _profiles_genesis_49_jpg from "./encoded/_profiles_genesis_49_jpg"
import _profiles_genesis_50_jpg from "./encoded/_profiles_genesis_50_jpg"
import _profiles_genesis_51_jpg from "./encoded/_profiles_genesis_51_jpg"
import _profiles_genesis_52_jpg from "./encoded/_profiles_genesis_52_jpg"
import _profiles_genesis_53_jpg from "./encoded/_profiles_genesis_53_jpg"
import _profiles_genesis_54_jpg from "./encoded/_profiles_genesis_54_jpg"
import _profiles_genesis_55_jpg from "./encoded/_profiles_genesis_55_jpg"
import _profiles_genesis_56_jpg from "./encoded/_profiles_genesis_56_jpg"
import _profiles_genesis_57_jpg from "./encoded/_profiles_genesis_57_jpg"
import _profiles_genesis_58_jpg from "./encoded/_profiles_genesis_58_jpg"
import _profiles_genesis_59_jpg from "./encoded/_profiles_genesis_59_jpg"
import _profiles_genesis_60_jpg from "./encoded/_profiles_genesis_60_jpg"
import _profiles_genesis_61_jpg from "./encoded/_profiles_genesis_61_jpg"
import _profiles_genesis_62_jpg from "./encoded/_profiles_genesis_62_jpg"
import _profiles_genesis_63_jpg from "./encoded/_profiles_genesis_63_jpg"
import _profiles_genesis_64_jpg from "./encoded/_profiles_genesis_64_jpg"
import _profiles_genesis_65_jpg from "./encoded/_profiles_genesis_65_jpg"
import _profiles_genesis_66_jpg from "./encoded/_profiles_genesis_66_jpg"
import _profiles_genesis_67_jpg from "./encoded/_profiles_genesis_67_jpg"
import _profiles_genesis_68_jpg from "./encoded/_profiles_genesis_68_jpg"
import _profiles_genesis_69_jpg from "./encoded/_profiles_genesis_69_jpg"
import _profiles_undefined_00_jpg from "./encoded/_profiles_undefined_00_jpg"

export const assets = {
  _profiles_bots_00_jpg: _profiles_bots_00_jpg,
  _profiles_bots_01_jpg: _profiles_bots_01_jpg,
  _profiles_bots_02_jpg: _profiles_bots_02_jpg,
  _profiles_bots_03_jpg: _profiles_bots_03_jpg,
  _profiles_characters_00_jpg: _profiles_characters_00_jpg,
  _profiles_characters_01_jpg: _profiles_characters_01_jpg,
  _profiles_characters_02_jpg: _profiles_characters_02_jpg,
  _profiles_characters_03_jpg: _profiles_characters_03_jpg,
  _profiles_characters_04_jpg: _profiles_characters_04_jpg,
  _profiles_genesis_00_jpg: _profiles_genesis_00_jpg,
  _profiles_genesis_01_jpg: _profiles_genesis_01_jpg,
  _profiles_genesis_02_jpg: _profiles_genesis_02_jpg,
  _profiles_genesis_03_jpg: _profiles_genesis_03_jpg,
  _profiles_genesis_04_jpg: _profiles_genesis_04_jpg,
  _profiles_genesis_05_jpg: _profiles_genesis_05_jpg,
  _profiles_genesis_06_jpg: _profiles_genesis_06_jpg,
  _profiles_genesis_07_jpg: _profiles_genesis_07_jpg,
  _profiles_genesis_08_jpg: _profiles_genesis_08_jpg,
  _profiles_genesis_09_jpg: _profiles_genesis_09_jpg,
  _profiles_genesis_10_jpg: _profiles_genesis_10_jpg,
  _profiles_genesis_11_jpg: _profiles_genesis_11_jpg,
  _profiles_genesis_12_jpg: _profiles_genesis_12_jpg,
  _profiles_genesis_13_jpg: _profiles_genesis_13_jpg,
  _profiles_genesis_14_jpg: _profiles_genesis_14_jpg,
  _profiles_genesis_15_jpg: _profiles_genesis_15_jpg,
  _profiles_genesis_16_jpg: _profiles_genesis_16_jpg,
  _profiles_genesis_17_jpg: _profiles_genesis_17_jpg,
  _profiles_genesis_18_jpg: _profiles_genesis_18_jpg,
  _profiles_genesis_19_jpg: _profiles_genesis_19_jpg,
  _profiles_genesis_20_jpg: _profiles_genesis_20_jpg,
  _profiles_genesis_21_jpg: _profiles_genesis_21_jpg,
  _profiles_genesis_22_jpg: _profiles_genesis_22_jpg,
  _profiles_genesis_23_jpg: _profiles_genesis_23_jpg,
  _profiles_genesis_24_jpg: _profiles_genesis_24_jpg,
  _profiles_genesis_25_jpg: _profiles_genesis_25_jpg,
  _profiles_genesis_26_jpg: _profiles_genesis_26_jpg,
  _profiles_genesis_27_jpg: _profiles_genesis_27_jpg,
  _profiles_genesis_28_jpg: _profiles_genesis_28_jpg,
  _profiles_genesis_29_jpg: _profiles_genesis_29_jpg,
  _profiles_genesis_30_jpg: _profiles_genesis_30_jpg,
  _profiles_genesis_31_jpg: _profiles_genesis_31_jpg,
  _profiles_genesis_32_jpg: _profiles_genesis_32_jpg,
  _profiles_genesis_33_jpg: _profiles_genesis_33_jpg,
  _profiles_genesis_34_jpg: _profiles_genesis_34_jpg,
  _profiles_genesis_35_jpg: _profiles_genesis_35_jpg,
  _profiles_genesis_36_jpg: _profiles_genesis_36_jpg,
  _profiles_genesis_37_jpg: _profiles_genesis_37_jpg,
  _profiles_genesis_38_jpg: _profiles_genesis_38_jpg,
  _profiles_genesis_39_jpg: _profiles_genesis_39_jpg,
  _profiles_genesis_40_jpg: _profiles_genesis_40_jpg,
  _profiles_genesis_41_jpg: _profiles_genesis_41_jpg,
  _profiles_genesis_42_jpg: _profiles_genesis_42_jpg,
  _profiles_genesis_43_jpg: _profiles_genesis_43_jpg,
  _profiles_genesis_44_jpg: _profiles_genesis_44_jpg,
  _profiles_genesis_45_jpg: _profiles_genesis_45_jpg,
  _profiles_genesis_46_jpg: _profiles_genesis_46_jpg,
  _profiles_genesis_47_jpg: _profiles_genesis_47_jpg,
  _profiles_genesis_48_jpg: _profiles_genesis_48_jpg,
  _profiles_genesis_49_jpg: _profiles_genesis_49_jpg,
  _profiles_genesis_50_jpg: _profiles_genesis_50_jpg,
  _profiles_genesis_51_jpg: _profiles_genesis_51_jpg,
  _profiles_genesis_52_jpg: _profiles_genesis_52_jpg,
  _profiles_genesis_53_jpg: _profiles_genesis_53_jpg,
  _profiles_genesis_54_jpg: _profiles_genesis_54_jpg,
  _profiles_genesis_55_jpg: _profiles_genesis_55_jpg,
  _profiles_genesis_56_jpg: _profiles_genesis_56_jpg,
  _profiles_genesis_57_jpg: _profiles_genesis_57_jpg,
  _profiles_genesis_58_jpg: _profiles_genesis_58_jpg,
  _profiles_genesis_59_jpg: _profiles_genesis_59_jpg,
  _profiles_genesis_60_jpg: _profiles_genesis_60_jpg,
  _profiles_genesis_61_jpg: _profiles_genesis_61_jpg,
  _profiles_genesis_62_jpg: _profiles_genesis_62_jpg,
  _profiles_genesis_63_jpg: _profiles_genesis_63_jpg,
  _profiles_genesis_64_jpg: _profiles_genesis_64_jpg,
  _profiles_genesis_65_jpg: _profiles_genesis_65_jpg,
  _profiles_genesis_66_jpg: _profiles_genesis_66_jpg,
  _profiles_genesis_67_jpg: _profiles_genesis_67_jpg,
  _profiles_genesis_68_jpg: _profiles_genesis_68_jpg,
  _profiles_genesis_69_jpg: _profiles_genesis_69_jpg,
  _profiles_undefined_00_jpg: _profiles_undefined_00_jpg,
}
