/* Autogenerated file. Do not edit manually. */
// from: ../../client/public/images/ui

// import _images_ui_card_pack_edge_png from "./encoded/_images_ui_card_pack_edge_png"
// import _images_ui_card_pack_flap_background_png from "./encoded/_images_ui_card_pack_flap_background_png"
// import _images_ui_card_pack_flap_inner_png from "./encoded/_images_ui_card_pack_flap_inner_png"
// import _images_ui_card_pack_flap_outter_png from "./encoded/_images_ui_card_pack_flap_outter_png"
// import _images_ui_card_pack_inner_png from "./encoded/_images_ui_card_pack_inner_png"
// import _images_ui_card_pack_outter_png from "./encoded/_images_ui_card_pack_outter_png"
// import _images_ui_card_pack_seal_background_png from "./encoded/_images_ui_card_pack_seal_background_png"
// import _images_ui_card_pack_seal_png from "./encoded/_images_ui_card_pack_seal_png"
// import _images_ui_card_pack_png from "./encoded/_images_ui_card_pack_png"
// import _images_ui_card_souls_png from "./encoded/_images_ui_card_souls_png"
import _images_ui_duel_paper_png from "./encoded/_images_ui_duel_paper_png"
// import _images_ui_hand_card_multiple_bottom_png from "./encoded/_images_ui_hand_card_multiple_bottom_png"
// import _images_ui_hand_card_multiple_top_png from "./encoded/_images_ui_hand_card_multiple_top_png"
// import _images_ui_hand_card_single_bottom_closed_png from "./encoded/_images_ui_hand_card_single_bottom_closed_png"
// import _images_ui_hand_card_single_bottom_open_png from "./encoded/_images_ui_hand_card_single_bottom_open_png"
// import _images_ui_hand_card_single_top_png from "./encoded/_images_ui_hand_card_single_top_png"
// import _images_ui_hand_sweep_png from "./encoded/_images_ui_hand_sweep_png"
// import _images_ui_hand_throw_png from "./encoded/_images_ui_hand_throw_png"
// import _images_ui_pistol_png from "./encoded/_images_ui_pistol_png"
// import _images_ui_seal_png from "./encoded/_images_ui_seal_png"

export const assets = {
  // _images_ui_card_pack_edge_png: _images_ui_card_pack_edge_png,
  // _images_ui_card_pack_flap_background_png: _images_ui_card_pack_flap_background_png,
  // _images_ui_card_pack_flap_inner_png: _images_ui_card_pack_flap_inner_png,
  // _images_ui_card_pack_flap_outter_png: _images_ui_card_pack_flap_outter_png,
  // _images_ui_card_pack_inner_png: _images_ui_card_pack_inner_png,
  // _images_ui_card_pack_outter_png: _images_ui_card_pack_outter_png,
  // _images_ui_card_pack_seal_background_png: _images_ui_card_pack_seal_background_png,
  // _images_ui_card_pack_seal_png: _images_ui_card_pack_seal_png,
  // _images_ui_card_pack_png: _images_ui_card_pack_png,
  // _images_ui_card_souls_png: _images_ui_card_souls_png,
  _images_ui_duel_paper_png: _images_ui_duel_paper_png,
  // _images_ui_hand_card_multiple_bottom_png: _images_ui_hand_card_multiple_bottom_png,
  // _images_ui_hand_card_multiple_top_png: _images_ui_hand_card_multiple_top_png,
  // _images_ui_hand_card_single_bottom_closed_png: _images_ui_hand_card_single_bottom_closed_png,
  // _images_ui_hand_card_single_bottom_open_png: _images_ui_hand_card_single_bottom_open_png,
  // _images_ui_hand_card_single_top_png: _images_ui_hand_card_single_top_png,
  // _images_ui_hand_sweep_png: _images_ui_hand_sweep_png,
  // _images_ui_hand_throw_png: _images_ui_hand_throw_png,
  // _images_ui_pistol_png: _images_ui_pistol_png,
  // _images_ui_seal_png: _images_ui_seal_png,
}
