kind = "DojoModel"
class_hash = "0x72a74999fc8e8c16d529ae335b0a240afffa58e368dbefa2692c3ba40dfad35"
original_class_hash = "0x72a74999fc8e8c16d529ae335b0a240afffa58e368dbefa2692c3ba40dfad35"
abi = "manifests/staging/base/abis/models/origami_token-ERC721EnumerableOwnerTokenModel-74966560.json"
tag = "origami_token-ERC721EnumerableOwnerTokenModel"
manifest_name = "origami_token-ERC721EnumerableOwnerTokenModel-74966560"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "index"
type = "u128"
key = false
