kind = "DojoModel"
class_hash = "0x6b05e10a9a84fe260a91833936740b56b77a8caff0cd9fd842f4b6e0ec95ec5"
original_class_hash = "0x6b05e10a9a84fe260a91833936740b56b77a8caff0cd9fd842f4b6e0ec95ec5"
abi = "manifests/staging/base/abis/models/pistols-TableConfig-1e8368fc.json"
tag = "pistols-TableConfig"
qualified_path = "pistols::models::table::table_config"
manifest_name = "pistols-TableConfig-1e8368fc"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "table_type"
type = "TableType"
key = false

[[members]]
name = "deck_type"
type = "DeckType"
key = false

[[members]]
name = "fee_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "fee_collector_address"
type = "ContractAddress"
key = false

[[members]]
name = "fee_min"
type = "u128"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
