kind = "DojoModel"
class_hash = "0x7bfd666c3bc1e5da819e40178efb3a59125b2e9b56241bed13496dfeed3d55c"
original_class_hash = "0x7bfd666c3bc1e5da819e40178efb3a59125b2e9b56241bed13496dfeed3d55c"
abi = "manifests/staging/base/abis/models/pistols-TableConfig-1e8368fc.json"
tag = "pistols-TableConfig"
qualified_path = "pistols::models::table::table_config"
manifest_name = "pistols-TableConfig-1e8368fc"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "table_type"
type = "TableType"
key = false

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "fee_collector_address"
type = "ContractAddress"
key = false

[[members]]
name = "fee_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "fee_min"
type = "u128"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
