kind = "DojoModel"
class_hash = "0x6ac45c2da58fd55c4a35dd4493316dfad2f20aaa88239fa29208e767133964b"
original_class_hash = "0x6ac45c2da58fd55c4a35dd4493316dfad2f20aaa88239fa29208e767133964b"
abi = "manifests/staging/base/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
qualified_path = "pistols::models::challenge::round"
manifest_name = "pistols-Round-617e0a3d"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "state"
type = "RoundState"
key = false

[[members]]
name = "shot_a"
type = "Shot"
key = false

[[members]]
name = "shot_b"
type = "Shot"
key = false
