kind = "DojoModel"
class_hash = "0x685e0b175c99e3aa54a52e770d7eee62f96cbdeccc4d0f308e4f32fe7c426fd"
original_class_hash = "0x685e0b175c99e3aa54a52e770d7eee62f96cbdeccc4d0f308e4f32fe7c426fd"
abi = "manifests/staging/base/abis/models/pistols-TokenConfig-56ebd338.json"
tag = "pistols-TokenConfig"
manifest_name = "pistols-TokenConfig-56ebd338"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "max_supply"
type = "u16"
key = false

[[members]]
name = "max_per_wallet"
type = "u16"
key = false

[[members]]
name = "minted_count"
type = "u16"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
