kind = "DojoModel"
class_hash = "0xc0aeb91970c9a9c1d7223c85f98ae64648f2219a946b5ec817b405ac4de66f"
original_class_hash = "0xc0aeb91970c9a9c1d7223c85f98ae64648f2219a946b5ec817b405ac4de66f"
abi = "manifests/staging/base/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
qualified_path = "pistols::models::challenge::round"
manifest_name = "pistols-Round-617e0a3d"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "state"
type = "RoundState"
key = false

[[members]]
name = "moves_a"
type = "Moves"
key = false

[[members]]
name = "moves_b"
type = "Moves"
key = false

[[members]]
name = "state_a"
type = "PlayerState"
key = false

[[members]]
name = "state_b"
type = "PlayerState"
key = false
