kind = "DojoModel"
class_hash = "0x20f685f8161947b75afae4199160eed56786bfef3cec3d23f39d4ac22305a8e"
original_class_hash = "0x20f685f8161947b75afae4199160eed56786bfef3cec3d23f39d4ac22305a8e"
abi = "manifests/staging/base/abis/models/pistols-Round-617e0a3d.json"
tag = "pistols-Round"
qualified_path = "pistols::models::challenge::round"
manifest_name = "pistols-Round-617e0a3d"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "moves_a"
type = "Moves"
key = false

[[members]]
name = "moves_b"
type = "Moves"
key = false

[[members]]
name = "state_a"
type = "PlayerState"
key = false

[[members]]
name = "state_b"
type = "PlayerState"
key = false

[[members]]
name = "state"
type = "RoundState"
key = false
