kind = "DojoContract"
class_hash = "0x25483853492c8ae171b14b3bde308fd7b0937abb80eace6183574d9175f050f"
original_class_hash = "0x25483853492c8ae171b14b3bde308fd7b0937abb80eace6183574d9175f050f"
base_class_hash = "0x0"
abi = "manifests/staging/base/abis/contracts/pistols-lords_mock-2b1156e6.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-lords_mock"
systems = [
    "faucet",
    "mint",
]
manifest_name = "pistols-lords_mock-2b1156e6"
