kind = "DojoContract"
class_hash = "0x5809efeb3c9c63821b16dc2e5656af7f951fb57ddd594c5281caddd65ce3d5c"
original_class_hash = "0x5809efeb3c9c63821b16dc2e5656af7f951fb57ddd594c5281caddd65ce3d5c"
base_class_hash = "0x0"
abi = "manifests/staging/base/abis/contracts/pistols-admin-36fd2037.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-admin"
systems = [
    "grant_admin",
    "set_config",
    "set_paused",
    "set_table",
    "set_table_admittance",
    "open_table",
]
manifest_name = "pistols-admin-36fd2037"
