kind = "DojoContract"
class_hash = "0x6bfa07ba209c48a9e9130b6dd35563ae8f189269914644660914a7addbb1df8"
original_class_hash = "0x6bfa07ba209c48a9e9130b6dd35563ae8f189269914644660914a7addbb1df8"
base_class_hash = "0x0"
abi = "manifests/staging/base/abis/contracts/pistols-admin-36fd2037.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-admin"
systems = [
    "grant_admin",
    "set_config",
    "set_paused",
    "set_table",
    "set_table_admittance",
    "open_table",
]
manifest_name = "pistols-admin-36fd2037"
