kind = "DojoContract"
class_hash = "0x64634471f3ceca08ceddc491e5d31155cf5049de4f2999d3addee2286cb0d55"
original_class_hash = "0x64634471f3ceca08ceddc491e5d31155cf5049de4f2999d3addee2286cb0d55"
base_class_hash = "0x0"
abi = "manifests/staging/base/abis/contracts/pistols-minter-7b759538.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-minter"
systems = ["set_open"]
manifest_name = "pistols-minter-7b759538"
