kind = "DojoContract"
class_hash = "0x2eb45abd14ca9d0b57f186c8343105f309a6a8faf02cbe1cf77afd58a7a6f07"
original_class_hash = "0x2eb45abd14ca9d0b57f186c8343105f309a6a8faf02cbe1cf77afd58a7a6f07"
base_class_hash = "0x0"
abi = "manifests/staging/base/abis/contracts/pistols-actions-4f10cff7.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-actions"
systems = [
    "commit_moves",
    "reveal_moves",
    "_emitDuelistRegisteredEvent",
    "_emitNewChallengeEvent",
    "_emitChallengeAcceptedEvent",
    "_emitPostRevealEvents",
    "_emitDuelistTurnEvent",
    "_emitChallengeResolvedEvent",
]
manifest_name = "pistols-actions-4f10cff7"
