kind = "DojoContract"
class_hash = "0x3f07a5354d58fb79bdfc6d540588f338fea31bb5d04142b211759d5f635dc15"
original_class_hash = "0x3f07a5354d58fb79bdfc6d540588f338fea31bb5d04142b211759d5f635dc15"
base_class_hash = "0x0"
abi = "manifests/staging/base/abis/contracts/pistols-duelist_token-45c96d20.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-duelist_token"
systems = ["delete_duelist"]
manifest_name = "pistols-duelist_token-45c96d20"
