tag = "pistols-duelist_token"
writes = [
  "pistols-TokenConfig",
  "pistols-Payment",
  "pistols-Duelist",
]
init_calldata = [
  "0", # "sstr:https://pistols.underware.gg", # base_uri
  "0x0", # minter_address
  "0x0", # renderer_address
  "100000000000000000000", # fee_amount: 100 LORDS
]
