kind = "DojoContract"
class_hash = "0x6730cb95389276478cdd6938c0589a402cbb1617eb97311efe07db31741a899"
original_class_hash = "0x6730cb95389276478cdd6938c0589a402cbb1617eb97311efe07db31741a899"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-duelist_token-45c96d20.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-duelist_token"
systems = ["delete_duelist"]
manifest_name = "pistols-duelist_token-45c96d20"
