kind = "DojoContract"
class_hash = "0x376c309325bbbda3f588535a79857aea27d0ffcd9c8ea0207ea3c1b11a4296a"
original_class_hash = "0x376c309325bbbda3f588535a79857aea27d0ffcd9c8ea0207ea3c1b11a4296a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-actions-4f10cff7.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-actions"
systems = [
    "commit_moves",
    "reveal_moves",
    "_emitDuelistRegisteredEvent",
    "_emitNewChallengeEvent",
    "_emitChallengeAcceptedEvent",
    "_emitPostRevealEvents",
    "_emitDuelistTurnEvent",
    "_emitChallengeResolvedEvent",
]
manifest_name = "pistols-actions-4f10cff7"
