kind = "DojoContract"
class_hash = "0x35affbecfa7f33649a4808b78cd16e6b85ca85f955b13776df8b9f5f55a7efa"
original_class_hash = "0x35affbecfa7f33649a4808b78cd16e6b85ca85f955b13776df8b9f5f55a7efa"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_token_duelist_token_duelist.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::token_duelist::token_duelist"
