kind = "DojoContract"
class_hash = "0x5b77527c0d56b8369b09ff224d3a81cadc04a04f8c6516e7ae5c32e27021536"
original_class_hash = "0x5b77527c0d56b8369b09ff224d3a81cadc04a04f8c6516e7ae5c32e27021536"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_minter_minter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::minter::minter"
