kind = "DojoContract"
class_hash = "0x6d6dbab1b15c220e33a5e9fd4091302a920ff2da18c6a2125672216c2de7895"
original_class_hash = "0x6d6dbab1b15c220e33a5e9fd4091302a920ff2da18c6a2125672216c2de7895"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-duel_token-670a5c67.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-duel_token"
systems = ["delete_duel"]
manifest_name = "pistols-duel_token-670a5c67"
