kind = "DojoContract"
class_hash = "0x72deaa6d685e6d6382667abdcf693535a3d91a744730c04981e08062e8bc79e"
original_class_hash = "0x72deaa6d685e6d6382667abdcf693535a3d91a744730c04981e08062e8bc79e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-duelist-5e4878f0.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-duelist"
systems = ["delete_duelist"]
manifest_name = "pistols-duelist-5e4878f0"
