kind = "DojoContract"
class_hash = "0x1beda69689b5fdc70da057f036cd7bd8b5f9a3c6d8ead533cdf488ae7fa33b4"
original_class_hash = "0x1beda69689b5fdc70da057f036cd7bd8b5f9a3c6d8ead533cdf488ae7fa33b4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-admin-36fd2037.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "pistols-admin"
manifest_name = "pistols-admin-36fd2037"
