kind = "DojoContract"
class_hash = "0x7b6937996af163bf20d46d164bad9eee3f0ecc2690b4c7894511d970cc785f1"
original_class_hash = "0x7b6937996af163bf20d46d164bad9eee3f0ecc2690b4c7894511d970cc785f1"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-actions-4f10cff7.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "pistols-actions"
manifest_name = "pistols-actions-4f10cff7"
