kind = "DojoContract"
class_hash = "0x32e3706f62c387ad898d6229181fe28722e6932fab371ed148436ea24ddf97c"
original_class_hash = "0x32e3706f62c387ad898d6229181fe28722e6932fab371ed148436ea24ddf97c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-fame_coin-371b95cb.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-fame_coin"
systems = [
    "minted_duelist",
    "updated_duelist",
    "before_update",
    "after_update",
]
manifest_name = "pistols-fame_coin-371b95cb"
