kind = "DojoContract"
class_hash = "0x5d165b4aa5592c789f1f356300242cb3d93ca25a337735c9974e1906cc5c005"
original_class_hash = "0x5d165b4aa5592c789f1f356300242cb3d93ca25a337735c9974e1906cc5c005"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_admin_admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::admin::admin"
