kind = "DojoContract"
class_hash = "0x4fe07935f6bde1eec37bce698dd1666ff7422e7427cecb5200fe02cedf542e8"
original_class_hash = "0x4fe07935f6bde1eec37bce698dd1666ff7422e7427cecb5200fe02cedf542e8"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-duelist_token-45c96d20.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-duelist_token"
systems = ["delete_duelist"]
manifest_name = "pistols-duelist_token-45c96d20"
