kind = "DojoContract"
class_hash = "0x4f7ed485fc8ed0c06f67f2ca9e529c8a705e7a892c3eb43e65a353eaf0395d3"
original_class_hash = "0x4f7ed485fc8ed0c06f67f2ca9e529c8a705e7a892c3eb43e65a353eaf0395d3"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_admin_admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::admin::admin"
