kind = "DojoContract"
class_hash = "0x207dfa75b727657355d13147ab9afbaac4d854db21344c77c46749a576d1872"
original_class_hash = "0x207dfa75b727657355d13147ab9afbaac4d854db21344c77c46749a576d1872"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_token_duelist_token_duelist.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::token_duelist::token_duelist"
