kind = "DojoContract"
class_hash = "0x7697c0077e4b010bce418f0ad91288f209d122f576f315b265a232e92e47129"
original_class_hash = "0x7697c0077e4b010bce418f0ad91288f209d122f576f315b265a232e92e47129"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-token_duelist-541e9c18.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-token_duelist"
systems = [
    "mint",
    "burn",
]
manifest_name = "pistols-token_duelist-541e9c18"
