kind = "DojoContract"
class_hash = "0x2811fe3f8b436c8123a9ce4a1ce56fcb0e9651717eebb82ead30298aa33a8ba"
original_class_hash = "0x2811fe3f8b436c8123a9ce4a1ce56fcb0e9651717eebb82ead30298aa33a8ba"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-admin-36fd2037.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-admin"
systems = [
    "grant_admin",
    "set_config",
    "set_paused",
    "set_table",
    "set_table_admittance",
    "open_table",
]
manifest_name = "pistols-admin-36fd2037"
