kind = "DojoContract"
class_hash = "0x665057d603061c5cdf00c12ec9798c3f98d3fb003446790ac7aa5125037f3d4"
original_class_hash = "0x665057d603061c5cdf00c12ec9798c3f98d3fb003446790ac7aa5125037f3d4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-duelist_token-45c96d20.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-duelist_token"
systems = ["delete_duelist"]
manifest_name = "pistols-duelist_token-45c96d20"
