kind = "DojoContract"
class_hash = "0x306a2fd79c90f6a7b3366e8e40898c29801d3b85f249ed038f0a82cc825a724"
original_class_hash = "0x306a2fd79c90f6a7b3366e8e40898c29801d3b85f249ed038f0a82cc825a724"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::actions::actions"
