kind = "DojoContract"
class_hash = "0x6cc5daae06c1b26695de5044f11005e7b9ea7211b95352156795b193cb8ff5e"
original_class_hash = "0x6cc5daae06c1b26695de5044f11005e7b9ea7211b95352156795b193cb8ff5e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-game-32c10283.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-game"
systems = [
    "commit_moves",
    "reveal_moves",
    "_emitDuelistRegisteredEvent",
    "_emitNewChallengeEvent",
    "_emitChallengeAcceptedEvent",
    "_emitPostRevealEvents",
    "_emitDuelistTurnEvent",
    "_emitChallengeResolvedEvent",
]
manifest_name = "pistols-game-32c10283"
