kind = "DojoContract"
class_hash = "0x10073481cb15c5c113230ba4020e565d13d59cc3e46357af2ad4dd842f361e1"
original_class_hash = "0x10073481cb15c5c113230ba4020e565d13d59cc3e46357af2ad4dd842f361e1"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-bank-7a683ab6.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-bank"
systems = ["charge"]
manifest_name = "pistols-bank-7a683ab6"
