kind = "DojoContract"
class_hash = "0x319d5f823cfdf61ef8a9520399f64d8efca886552064bc23e22eb0e3cd9792a"
original_class_hash = "0x319d5f823cfdf61ef8a9520399f64d8efca886552064bc23e22eb0e3cd9792a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-lords_mock-2b1156e6.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-lords_mock"
systems = [
    "faucet",
    "mint",
]
manifest_name = "pistols-lords_mock-2b1156e6"
