kind = "DojoContract"
class_hash = "0x52d5ad475e9b61d4dc9b47962f9bc1e218a9419cee1e2898a7ff1706cc69715"
original_class_hash = "0x52d5ad475e9b61d4dc9b47962f9bc1e218a9419cee1e2898a7ff1706cc69715"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_minter_minter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::minter::minter"
