kind = "DojoContract"
class_hash = "0x6931ee544fd1ae80cc68cd5911bfea231eb2f2277b4571a2bf1b71d78c45ef"
original_class_hash = "0x6931ee544fd1ae80cc68cd5911bfea231eb2f2277b4571a2bf1b71d78c45ef"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-game-32c10283.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-game"
systems = [
    "commit_moves",
    "reveal_moves",
]
manifest_name = "pistols-game-32c10283"
