kind = "DojoContract"
class_hash = "0xcbdf8afd1312ba770cbe09926c47837465c2ba21fcef3a3647d164b2a6722"
original_class_hash = "0xcbdf8afd1312ba770cbe09926c47837465c2ba21fcef3a3647d164b2a6722"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols-game-32c10283.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-game"
systems = [
    "commit_moves",
    "reveal_moves",
]
manifest_name = "pistols-game-32c10283"
