kind = "DojoContract"
class_hash = "0x1ca9fe17ce5fca6acd2f8bc4a098f50351fc8bc17b090c971eaf29a15fe6a56"
original_class_hash = "0x1ca9fe17ce5fca6acd2f8bc4a098f50351fc8bc17b090c971eaf29a15fe6a56"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/pistols_systems_admin_admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::admin::admin"
