kind = "DojoContract"
class_hash = "0x5f0279f37252892df8bd7770aed1a8a3416bbcdbc10523ff23726bb0e3ccbcd"
original_class_hash = "0x5f0279f37252892df8bd7770aed1a8a3416bbcdbc10523ff23726bb0e3ccbcd"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::actions::actions"
