kind = "DojoContract"
class_hash = "0x4acc3c0e16e5dce496c22e49430fd1c44bd48081c654f54408a04b26d687ac7"
original_class_hash = "0x4acc3c0e16e5dce496c22e49430fd1c44bd48081c654f54408a04b26d687ac7"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/pistols-token_duelist-541e9c18.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-token_duelist"
systems = [
    "mint",
    "burn",
]
manifest_name = "pistols-token_duelist-541e9c18"
