kind = "DojoContract"
class_hash = "0x598797de2d0b81d9c3dd6e51490d77fd849afb9476bebff79329d72cb20664b"
original_class_hash = "0x598797de2d0b81d9c3dd6e51490d77fd849afb9476bebff79329d72cb20664b"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/pistols_mocks_lords_mock_lords_mock.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::mocks::lords_mock::lords_mock"
