kind = "DojoContract"
class_hash = "0xc3da78de3d60e208a046c0cae3104b47872ddad3c263b8b22f97653dfb6f45"
original_class_hash = "0xc3da78de3d60e208a046c0cae3104b47872ddad3c263b8b22f97653dfb6f45"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/pistols-minter-7b759538.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-minter"
systems = ["set_open"]
manifest_name = "pistols-minter-7b759538"
