kind = "DojoContract"
class_hash = "0x473be66ce5304722be5595a5986b2ccac54d8e97d0d6546070fa9957f544b3f"
original_class_hash = "0x473be66ce5304722be5595a5986b2ccac54d8e97d0d6546070fa9957f544b3f"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/pistols-actions-4f10cff7.json"
reads = []
writes = []
init_calldata = []
tag = "pistols-actions"
systems = [
    "commit_action",
    "reveal_action",
    "_emitDuelistRegisteredEvent",
    "_emitNewChallengeEvent",
    "_emitChallengeAcceptedEvent",
    "_emitPostRevealEvents",
    "_emitDuelistTurnEvent",
    "_emitChallengeResolvedEvent",
]
manifest_name = "pistols-actions-4f10cff7"
