tag = "pistols-admin"
writes = [
  "pistols-Config",
  "pistols-TableConfig",
  "pistols-TableAdmittance",
]
init_calldata = [
  "0x0",  # owner (or initializer)
  "0x0",  # treasury (or initializer)
  "0x044e6bcc627e6201ce09f781d1aae44ea4c21c2fdef299e34fce55bef2d02210", # lords contract
]
