tag = "pistols-admin"
writes = [
  "ns:pistols",
]
init_calldata = [
  "0x0",  # treasury_address (or initializer)
  "0x044e6bcc627e6201ce09f781d1aae44ea4c21c2fdef299e34fce55bef2d02210", # lords_address
]
