tag = "pistols-duel_token"
writes = [
  "pistols-TokenConfig",
  "pistols-Payment",
  "pistols-Challenge",
  "pistols-Round",
  "pistols-Pact",
  "pistols-Scoreboard",
]
init_calldata = [
  "0x0", # minter_address
  "0x0", # renderer_address
  "0", # fee_amount
]
