tag = "pistols-duelist_token"
writes = [
  "pistols-TokenConfig",
  "pistols-Duelist",
]
init_calldata = [
  "0x0", # minter_address
  "0x0", # renderer_address
  "100000000000000000000", # fee_amount: 100 LORDS
]
