tag = "pistols-minter"
writes = [
  "pistols-TokenConfig",
]
init_calldata = [
  "$contract_address:pistols-duelist_token", # duelist token
  "10000",  # max supply
  "100",    # max per wallet
  "1",      # is_open
]
